using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using IAX.IXApi.Modules.ERP.Shared.Features;
using IAX.IXApi.Shared.Domain.Entities;
using IAX.IXApi.Modules.ERP.Entities;
using IAX.IXApi.Modules.Organization.Employees.Entities;
using IAX.IXApi.Modules.Administration.AuditLogs.Entities;
using IAX.IXApi.Modules.Administration.DataManagement.Contracts;
using IAX.IXApi.Infrastructure.Persistence.Seeding.Entities;
using IAX.IXApi.Modules.ERP.Common;

namespace IAX.IXApi.Modules.ERP.AccountsReceivable
{
    [Table("MarkupTrans")]
    public class MarkupTrans : Entity<long>
    {
        //----------------------------------------- Core Information
        // Basic Properties
        [StringLength(FieldLengths.MarkupCode)]
        public string MarkupCode { get; set; } = string.Empty;
        public decimal LineNum { get; set; }
        public DateTime TransDate { get; set; }
        [StringLength(FieldLengths.Txt)]
        public string Txt { get; set; } = string.Empty;
        [StringLength(FieldLengths.Voucher)]
        public string Voucher { get; set; } = string.Empty;

        // Enum Properties
        public MarkupCategory MarkupCategory { get; set; }
        public MarkupModuleCategory ModuleCategory { get; set; }
        public MarkupModuleType ModuleType { get; set; }

        // ==========================================================
        // Poly-Contextual References (TransTableId & TransRecId mapping)
        // ==========================================================
        // Basic Properties
        public long TransRecId { get; set; }
        public int TransTableId { get; set; }
        public long OrigRecId { get; set; }
        public int OrigTableId { get; set; }

        // ==========================================================
        // Financial Values & Calculations
        // ==========================================================
        // Basic Properties
        [StringLength(FieldLengths.CurrencyCode)]
        public string CurrencyCode { get; set; } = string.Empty;
        public decimal Value { get; set; }
        public decimal Posted { get; set; }
        public decimal PreviousValue { get; set; }
        public decimal CalculatedAmount { get; set; }
        public decimal CalculatedAmountMst_W { get; set; }
        public decimal CalculatedProratedAmount { get; set; }
        public decimal FromAmount { get; set; }
        public decimal ToAmount { get; set; }

        // Enum Properties
        public NoYes Keep { get; set; }
        public NoYes IsCompound { get; set; }
        public NoYes IsAutoCharge { get; set; }
        public NoYes IsTieredCharge { get; set; }
        public NoYes IsAdvancedLineProrated { get; set; }

        // ==========================================================
        // Tax
        // ==========================================================
        // Basic Properties
        [StringLength(FieldLengths.TaxGroup)]
        public string TaxGroup { get; set; } = string.Empty;
        [StringLength(FieldLengths.TaxItemGroup)]
        public string TaxItemGroup { get; set; } = string.Empty;
        public decimal TaxAmount { get; set; }
        public decimal TaxAmountMst_W { get; set; }
        public long TaxWithholdItemGroup { get; set; }
        public decimal TaxExemptPriceInclusiveOriginalPrice { get; set; }
        public decimal TaxExemptPriceInclusiveReductionAmount { get; set; }

        // Enum Properties
        public NoYes OverrideSalesTax { get; set; }
        public NoYes TaxAutoGenerated { get; set; }

        // ==========================================================
        // Intercompany Tracking
        // ==========================================================
        // Basic Properties
        public long IntercompanyRefRecId { get; set; }
        public decimal IntercompanyMarkupValue { get; set; }

        // Enum Properties
        public NoYes IntercompanyMarkupUseValue { get; set; }

        // ==========================================================
        // Call Center & Retail (MCR / Promotion)
        // ==========================================================
        // Basic Properties
        public decimal McrOriginalMiscChargeValue { get; set; }
        public long McrSavedRecId { get; set; }
        public int McrSavedTableId { get; set; }
        public decimal RetailShippingPromotionDiscount { get; set; }

        // Enum Properties
        public NoYes McrBrokerContractFee { get; set; }
        public NoYes McrCouponMarkup { get; set; }
        public NoYes McrInstallmentEligible { get; set; }
        public NoYes McrMiscChargeOverride { get; set; }
        public int McrMarkupTransCreatedBy { get; set; }

        // ==========================================================
        // Invoicing Templates & Sub-Ledger Diagnostics
        // ==========================================================
        // Basic Properties
        public long CustInvoiceLineIdRef { get; set; }
        public long CustInvoiceLineTemplate { get; set; }
        public long VendInvoiceLineTemplate { get; set; }
        public long VendInvoiceTableMarkupTrans { get; set; }
        public long VendInvoiceTemplate { get; set; }
        public long ItemBasePriceRecId { get; set; }
        public long MarkupAutoLineRecId { get; set; }
        public long MarkupAutoTableRecId { get; set; }
        public long SourceDocumentLine { get; set; }

        // ==========================================================
        // System Flags & Audit Trailing
        // ==========================================================
        // Basic Properties
        public int Sequence { get; set; }
        public int Position { get; set; }
        public long CorrectedMarkupTrans { get; set; }

        // Enum Properties
        public DocumentStatus DocumentStatus { get; set; }
        public NoYes IsModified { get; set; }
        public NoYes IsDeleted { get; set; }
        public NoYes IsOverriddenLine { get; set; }
        public NoYes IsOverriddenProratedLine { get; set; }


        #region Navigation Properties Row

//         [ForeignKey(nameof(CurrencyCode))]
//         public virtual Currency? Currency { get; set; }

//         [ForeignKey(nameof(MarkupCode))]
//         public virtual MarkupTable? AssociatedMarkup { get; set; }

        // Generic reflection hooks can be linked dynamically in data-context definitions via TableId maps.
        // E.g., if TransTableId matches SalesTable's TableId, this targets a SalesTable record header.

        #endregion
    }
}
