using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using IAX.IXApi.Modules.Finance.Shared.Features;
using IAX.IXApi.Shared.Domain.Entities;
using IAX.IXApi.Modules.Finance.Entities;
using IAX.IXApi.Modules.Organization.Employees.Entities;
using IAX.IXApi.Modules.Finance.Common;

namespace IAX.IXApi.Modules.Finance.AccountsReceivable
{
    [Table("CustInvoiceLine")]
    public class CustInvoiceLine : Entity<long>
    {
        //----------------------------------------- Core Information
        // Basic Properties
        public decimal LineNum { get; set; }
        [StringLength(FieldLengths.Description)]
        public string Description { get; set; } = string.Empty;
        public string? InvoiceTxt { get; set; } // Nullable nvarchar(MAX)

        // ==========================================================
        // Financials & Quantities
        // ==========================================================
        // Basic Properties
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal AmountCur { get; set; }
        public string? AmountDetails { get; set; } // Nullable nvarchar(MAX)
        public decimal Weight { get; set; }

        // ==========================================================
        // Billing Codes & Templates
        // ==========================================================
        // Basic Properties
        [StringLength(FieldLengths.Code)]
        public string BillingCode { get; set; } = string.Empty;
        public long CustBillingCode { get; set; }
        public long CustInvoiceLineTemplate { get; set; }
        public DateTime PeriodChargeInvoiceLineBaseFromDate { get; set; }
        public DateTime PeriodChargeInvoiceLineBaseToDate { get; set; }

        // ==========================================================
        // Ledger & Dimensions
        // ==========================================================
        // Basic Properties
        public long LedgerDimension { get; set; }
        public long DefaultDimension { get; set; }
        public long AccountingDistributionTemplate { get; set; }

        // ==========================================================
        // Tax
        // ==========================================================
        // Basic Properties
        [StringLength(FieldLengths.TaxGroup)]
        public string TaxGroup { get; set; } = string.Empty;
        [StringLength(FieldLengths.TaxItemGroup)]
        public string TaxItemGroup { get; set; } = string.Empty;
        [StringLength(FieldLengths.TaxWithholdGroup)]
        public string TaxWithholdGroup { get; set; } = string.Empty;
        public decimal TaxAmount { get; set; }

        // Enum Properties
        public NoYes OverrideSalesTax { get; set; }
        public NoYes TaxAutoGenerated { get; set; }

        // ==========================================================
        // Fixed Assets
        // ==========================================================
        // Basic Properties
        [StringLength(FieldLengths.Num)]
        public string AssetId { get; set; } = string.Empty;
        [StringLength(FieldLengths.Num)]
        public string AssetBookId { get; set; } = string.Empty;

        // ==========================================================
        // References & System Tracking
        // ==========================================================
        // Basic Properties
        public long ParentRecId { get; set; } // Contextual header link
        public long CorrectedCustInvoiceLine { get; set; }
        public long RefReturnInvoiceTrans_W { get; set; }
        public long ProjFundingSource { get; set; }
        public long IntrastatCommodity { get; set; }
        public long SourceDocumentLine { get; set; }
        public long ReasonRefRecId { get; set; }
        public long FinTag { get; set; }

        // Enum Properties
        public SysDataStateCode SysDataStateCode { get; set; }


        #region Navigation Properties Row

//         [ForeignKey(nameof(ParentRecId))]
//         public virtual CustInvoiceTable? CustInvoiceTable { get; set; }

//         [ForeignKey(nameof(DefaultDimension))]
//         public virtual DimensionAttributeValueSet? DimensionAttributeValueSet { get; set; }

//         [ForeignKey(nameof(LedgerDimension))]
//         public virtual DimensionAttributeValueCombination? DimensionAttributeValueCombination { get; set; }

//         [ForeignKey(nameof(TaxGroup))]
//         public virtual TaxGroupHeading? TaxGroupHeading { get; set; }

//         [ForeignKey(nameof(TaxItemGroup))]
//         public virtual TaxItemGroupHeading? TaxItemGroupHeading { get; set; }

        #endregion
    }
}

