export const d365 = {
  fontFamily: '"Segoe UI", "Segoe UI Web (West European)", Arial, sans-serif',
  fontSize: 12,
  labelFontSize: 10,
  titleFontSize: 20,
  primary: '#315efb',
  text: '#1b1a19',
  mutedText: '#605e5c',
  canvas: '#faf9f8',
  surface: '#ffffff',
  border: '#c8c6c4',
  darkBorder: '#8a8886',
  selectedRow: '#d4e0f7',
  selectedBar: '#315efb',
  disabledFill: '#f3f2f1',
  toolbarHeight: 41,
  controlHeight: 30,
  sectionHeaderHeight: 45,
  gridHeaderHeight: 32,
  gridRowHeight: 31,
  listWidth: 281,
  utilityRailWidth: 60,
  radius: 2,
  sectionRadius: 7,
  sectionGap: 5,
  fieldGap: 10,
} as const;
