using IAX.IXApi.Modules.Finance.AccountsReceivable;
using IAX.IXApi.Modules.Finance.Common;
using IAX.IXApi.Modules.Finance.Entities;
using Mapster;

namespace IAX.IXApi.Modules.Finance.Foundation.Markup;

public sealed class MarkupMapping : IRegister
{
    public void Register(TypeAdapterConfig config)
    {
        // Preserve the existing response fields and inherited DTO defaults.
        config.NewConfig<MarkupTrans, MarkupTransDto>()
            .IgnoreNonMapped(true)
            .Map(d => d.RecId, s => s.RecId)
            .Map(d => d.DataAreaId, s => s.DataAreaId)
            .Map(d => d.MarkupCode, s => s.MarkupCode)
            .Map(d => d.LineNum, s => s.LineNum)
            .Map(d => d.TransDate, s => s.TransDate)
            .Map(d => d.Txt, s => s.Txt)
            .Map(d => d.Voucher, s => s.Voucher)
            .Map(d => d.MarkupCategory, s => s.MarkupCategory)
            .Map(d => d.ModuleCategory, s => s.ModuleCategory)
            .Map(d => d.ModuleType, s => s.ModuleType)
            .Map(d => d.TransRecId, s => s.TransRecId)
            .Map(d => d.TransTableId, s => s.TransTableId)
            .Map(d => d.OrigRecId, s => s.OrigRecId)
            .Map(d => d.OrigTableId, s => s.OrigTableId)
            .Map(d => d.CurrencyCode, s => s.CurrencyCode)
            .Map(d => d.Value, s => s.Value)
            .Map(d => d.Posted, s => s.Posted)
            .Map(d => d.PreviousValue, s => s.PreviousValue)
            .Map(d => d.CalculatedAmount, s => s.CalculatedAmount)
            .Map(d => d.CalculatedProratedAmount, s => s.CalculatedProratedAmount)
            .Map(d => d.FromAmount, s => s.FromAmount)
            .Map(d => d.ToAmount, s => s.ToAmount)
            .Map(d => d.Keep, s => s.Keep)
            .Map(d => d.IsCompound, s => s.IsCompound)
            .Map(d => d.IsAutoCharge, s => s.IsAutoCharge)
            .Map(d => d.IsTieredCharge, s => s.IsTieredCharge)
            .Map(d => d.TaxGroup, s => s.TaxGroup)
            .Map(d => d.TaxItemGroup, s => s.TaxItemGroup)
            .Map(d => d.TaxAmount, s => s.TaxAmount)
            .Map(d => d.OverrideSalesTax, s => s.OverrideSalesTax)
            .Map(d => d.TaxAutoGenerated, s => s.TaxAutoGenerated)
            .Map(d => d.McrBrokerContractFee, s => s.McrBrokerContractFee)
            .Map(d => d.IntercompanyRefRecId, s => s.IntercompanyRefRecId)
            .Map(d => d.IntercompanyMarkupValue, s => s.IntercompanyMarkupValue)
            .Map(d => d.DocumentStatus, s => s.DocumentStatus);

        // Only editable request fields may change an existing charge.
        config.NewConfig<MarkupTransDto, MarkupTrans>()
            .IgnoreNonMapped(true)
            .Map(d => d.MarkupCode, s => s.MarkupCode.Trim())
            .Map(d => d.Txt, s => s.Txt != null ? s.Txt.Trim() : string.Empty)
            .Map(d => d.MarkupCategory, s => s.MarkupCategory)
            .Map(d => d.CurrencyCode, s => s.CurrencyCode != null ? s.CurrencyCode.Trim().ToUpperInvariant() : string.Empty)
            .Map(d => d.Value, s => s.Value)
            .Map(d => d.Keep, s => s.Keep)
            .Map(d => d.McrBrokerContractFee, s => s.McrBrokerContractFee)
            .Map(d => d.TaxGroup, s => s.TaxGroup != null ? s.TaxGroup.Trim().ToUpperInvariant() : string.Empty)
            .Map(d => d.TaxItemGroup, s => s.TaxItemGroup != null ? s.TaxItemGroup.Trim().ToUpperInvariant() : string.Empty)
            .Map(d => d.Voucher, s => s.Voucher != null ? s.Voucher.Trim() : string.Empty)
            .Map(d => d.CalculatedAmount, s => s.CalculatedAmount)
            .Map(d => d.IntercompanyRefRecId, s => s.IntercompanyRefRecId)
            .Map(d => d.IntercompanyMarkupValue, s => s.IntercompanyMarkupValue)
            .Map(d => d.IsModified, s => NoYes.Yes);

        config.NewConfig<MarkupTable, MarkupCodeDto>();
    }
}
