using System;
using System.ComponentModel.DataAnnotations;
using IAX.IXApi.Shared.Application.Contracts;
using IAX.IXApi.Modules.ERP.Common;

namespace IAX.IXApi.Modules.ERP.Shared.Features
{
    public class MarkupTableDto : EntityDto<long>
    {
        public string DataAreaId { get; set; } = "dat";

        [Required]
        [StringLength(FieldLengths.MarkupCode)]
        public string MarkupCode { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.Txt)]
        public string Txt { get; set; } = string.Empty;

        public string CurrencyCode { get; set; } = string.Empty;

        public ModuleInventPurchSales ModuleType { get; set; }

        public string TaxItemGroup { get; set; } = string.Empty;

        public string? ZatcaNominalCode { get; set; }

        public long TaxRateType { get; set; }

        public long TaxWithholdItemGroup { get; set; }

        // Debit Posting
        public int CustType { get; set; }
        public int CustPosting { get; set; }
        public long? CustomerLedgerDimension { get; set; }

        // Bank Document Charge
        public NoYes IsBankDocumentCharge { get; set; }

        // Credit Posting
        public int VendType { get; set; }
        public int VendPosting { get; set; }
        public long? VendorLedgerDimension { get; set; }


        // Foreign Trade
        public NoYes IncludeIntoIntrastatInvoiceValue { get; set; }
        public NoYes IncludeIntoIntrastatStatisticalValue { get; set; }

        // Logistics & MCR
        public NoYes IsShipping { get; set; }
        public NoYes Refundable { get; set; }
        public NoYes McrProrate { get; set; }
        public NoYes McrBrokerContractFee { get; set; }
    }

    public class MarkupTransDto : EntityDto<long>
    {
        public string MarkupCode { get; set; } = string.Empty;
        public decimal LineNum { get; set; }
        public DateTime TransDate { get; set; }
        public string Txt { get; set; } = string.Empty;
        public string Voucher { get; set; } = string.Empty;
        public MarkupCategory MarkupCategory { get; set; }
        public MarkupModuleCategory ModuleCategory { get; set; }
        public MarkupModuleType ModuleType { get; set; }
        public long TransRecId { get; set; }
        public int TransTableId { get; set; }
        public long OrigRecId { get; set; }
        public int OrigTableId { get; set; }
        public string CurrencyCode { get; set; } = string.Empty;
        public decimal Value { get; set; }
        public decimal Posted { get; set; }
        public decimal PreviousValue { get; set; }
        public decimal CalculatedAmount { get; set; }
        public decimal CalculatedProratedAmount { get; set; }
        public decimal FromAmount { get; set; }
        public decimal ToAmount { get; set; }
        public NoYes Keep { get; set; }
        public NoYes IsCompound { get; set; }
        public NoYes IsAutoCharge { get; set; }
        public NoYes IsTieredCharge { get; set; }
        public string TaxGroup { get; set; } = string.Empty;
        public string TaxItemGroup { get; set; } = string.Empty;
        public decimal TaxAmount { get; set; }
        public NoYes OverrideSalesTax { get; set; }
        public NoYes TaxAutoGenerated { get; set; }
        public DocumentStatus DocumentStatus { get; set; }
    }
}
