import React, { useState, useMemo } from 'react';
import {
    Stack, Box, Typography, Chip, TextField, FormControlLabel, Switch,
    FormControl, InputLabel, Select, MenuItem, Button, Divider, Paper, IconButton,
    Accordion, AccordionSummary, AccordionDetails
} from '@mui/material';
import { useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ExpandMore, Add, Delete, AccountTree } from '@mui/icons-material';
import type { Transition } from '../../types';
import { uid } from '../../utils/uid';
import { BilingualField } from '../../../../../../components/common/BilingualField';
import { GeneratableTextField } from '../../../../../../components/common/GeneratableTextField';
import { ConditionBuilder } from '../shared/ConditionBuilder';
import { useProcessBuilderContext } from '../../context/ProcessBuilderContext';
import { useProcessBuilderData } from '../../hooks/useProcessBuilderData';
import { getAutoGeneratedMessage, getValidationTypesForControl } from '../../../../utils/validationHelper';

// =========================================================================
// Mask patterns and expression hints (same as RequestControlSettingsPanel)
// =========================================================================
interface MaskPattern { label: string; mask: string; validationType?: string; regex?: string; }

const MASK_PATTERNS: MaskPattern[] = [
    { label: 'Phone (US)',       mask: '000-000-0000',                     validationType: 'Phone',            regex: '^\\d{3}-\\d{3}-\\d{4}$' },
    { label: 'Phone (Intl)',     mask: '+000 000 000 0000',                validationType: 'Phone',            regex: '^\\+\\d{1,3} \\d{3} \\d{3} \\d{4}$' },
    { label: 'Mobile (SA)',      mask: '+966 00 000 0000',                 validationType: 'Mobile',           regex: '^\\+966 \\d{2} \\d{3} \\d{4}$' },
    { label: 'National ID (SA)', mask: '0000000000',                       validationType: 'NationalID',       regex: '^\\d{10}$' },
    { label: 'IBAN (SA)',        mask: 'SA00 0000 0000 0000 0000 0000',    validationType: 'IBAN',             regex: '^SA\\d{22}$' },
    { label: 'Credit Card',      mask: '0000 0000 0000 0000',              validationType: 'CreditCardFormat', regex: '^\\d{16}$' },
    { label: 'Passport (SA)',    mask: 'a0000000',                         validationType: 'PassportNumber',   regex: '^[A-Z]{1}\\d{7}$' },
    { label: 'Tax Number (SA)',  mask: '000000000000000',                  validationType: 'TaxNumber',        regex: '^\\d{15}$' },
];

const VALIDATION_TYPE_TO_MASK: Record<string, string> = Object.fromEntries(
    MASK_PATTERNS
        .filter((p): p is MaskPattern & { validationType: string } => !!p.validationType && p.validationType !== 'Regex')
        .map((p) => [p.validationType, p.mask])
);
const MASK_TYPES = new Set([...Object.keys(VALIDATION_TYPE_TO_MASK), 'Regex']);

interface ExpressionHint { placeholder: string; hint: string; }
const EXPRESSION_HINTS: Record<string, ExpressionHint> = {
    MinLength:          { placeholder: 'e.g. 5',                            hint: 'Minimum number of characters required' },
    MaxLength:          { placeholder: 'e.g. 255',                          hint: 'Maximum number of characters allowed' },
    ExactLength:        { placeholder: 'e.g. 10',                           hint: 'Exact number of characters' },
    Regex:              { placeholder: 'e.g. ^[A-Z]{3}[0-9]+$',            hint: 'Regex pattern the value must fully match' },
    StartsWith:         { placeholder: 'e.g. INV-',                         hint: 'Value must begin with this prefix' },
    EndsWith:           { placeholder: 'e.g. .pdf',                         hint: 'Value must end with this suffix' },
    Contains:           { placeholder: 'e.g. @company.com',                 hint: 'Value must include this substring' },
    DoesNotContain:     { placeholder: 'e.g. admin',                        hint: 'Value must NOT include this substring' },
    AllowedValues:      { placeholder: 'e.g. active,inactive,pending',      hint: 'Comma-separated list of permitted values' },
    ForbiddenValues:    { placeholder: 'e.g. null,undefined,N/A',           hint: 'Comma-separated list of disallowed values' },
    MinValue:           { placeholder: 'e.g. 0',                            hint: 'Value must be >= this number' },
    MaxValue:           { placeholder: 'e.g. 1000000',                      hint: 'Value must be <= this number' },
    Range:              { placeholder: 'e.g. 1-100',                        hint: 'Format: min-max (dash-separated)' },
    DecimalPrecision:   { placeholder: 'e.g. 2',                            hint: 'Maximum decimal places' },
    DateRange:          { placeholder: 'e.g. 2024-01-01|2024-12-31',        hint: 'Format: startDate|endDate (pipe-separated)' },
    MinimumAge:         { placeholder: 'e.g. 18',                           hint: 'Minimum age in years' },
    MaximumAge:         { placeholder: 'e.g. 65',                           hint: 'Maximum age in years' },
    Phone:              { placeholder: 'e.g. ^\\d{3}-\\d{3}-\\d{4}$',       hint: 'Regex for phone format' },
    Mobile:             { placeholder: 'e.g. ^\\+966\\d{9}$',               hint: 'Regex for mobile format' },
    NationalID:         { placeholder: 'e.g. ^[0-9]{10}$',                  hint: 'Regex for national ID' },
    TaxNumber:          { placeholder: 'e.g. ^[0-9]{15}$',                  hint: 'Regex for tax number' },
    PassportNumber:     { placeholder: 'e.g. ^[A-Z]{1}[0-9]{7}$',          hint: 'Regex for passport' },
    IBAN:               { placeholder: 'e.g. ^SA[0-9]{22}$',                hint: 'Regex for IBAN' },
    CreditCardFormat:   { placeholder: 'e.g. ^[0-9]{16}$',                  hint: 'Regex for credit card' },
    AllowedExtensions:  { placeholder: 'e.g. .pdf,.xlsx,.docx',             hint: 'Permitted file extensions (with dot)' },
    BlockedExtensions:  { placeholder: 'e.g. .exe,.bat,.sh',                hint: 'Blocked file extensions (with dot)' },
    MaxFileSize:        { placeholder: 'e.g. 5',                            hint: 'Max file size in MB' },
    MinFileSize:        { placeholder: 'e.g. 0.1',                          hint: 'Min file size in MB' },
    MaxNumberOfFiles:   { placeholder: 'e.g. 3',                            hint: 'Max number of files' },
    MinSelectedItems:   { placeholder: 'e.g. 1',                            hint: 'Min items that must be selected' },
    MaxSelectedItems:   { placeholder: 'e.g. 5',                            hint: 'Max items that can be selected' },
    ExactSelectedItems: { placeholder: 'e.g. 3',                            hint: 'Exact items that must be selected' },
    Expression:         { placeholder: 'e.g. {Amount} > 1000',              hint: 'Boolean expression using {field_code}' },
    CrossField:         { placeholder: 'e.g. {EndDate} > {StartDate}',      hint: 'Cross-field comparison' },
    Conditional:        { placeholder: "e.g. {Status} == 'active'",         hint: 'Condition that must be true' },
    CustomExpression:   { placeholder: 'e.g. {Amount} >= {MinAmount}',      hint: 'Custom boolean expression using {field_code}' },
};

// =========================================================================
// ActivityControlSettingsPanel
// =========================================================================

export const ActivityControlSettingsPanel: React.FC = React.memo(() => {
    const { i18n, t } = useTranslation();
    const isRtl = i18n.language === 'ar';
    const { id: routeId } = useParams<{ id: string }>();
    const isEditMode = !!routeId && routeId !== 'new';

    const {
        processInfo, steps, updateControl, selectedNode,
        variables, requestControls, transitions, setTransitions,
        updateTransition, deleteTransition,
        requestControlsValidations, addActivityControlsValidation,
        updateRequestControlsValidation, deleteRequestControlsValidation,
    } = useProcessBuilderContext();

    const { saveActivityToBackend, operators } = useProcessBuilderData(processInfo.id, isEditMode, true);

    const [saving, setSaving] = useState(false);
    const [showErrors, setShowErrors] = useState(false);

    const allFieldNames = useMemo(() => {
        const names: string[] = variables.map((v) => v.name);
        requestControls.forEach((c) => names.push(c.name));
        steps.forEach((s) => s.activities.forEach((a) => a.controls.forEach((c) => names.push(c.name))));
        return names;
    }, [variables, requestControls, steps]);

    if (selectedNode.kind !== 'control') return null;
    const { stepId, activityId, id } = selectedNode;
    const step = steps.find(s => s.id === stepId);
    const activity = step?.activities.find(a => a.id === activityId);
    const control = activity?.controls.find(c => c.id === id);
    if (!step || !activity || !control) return null;

    const errors = showErrors ? {
        label: !(isRtl ? control.labelAR : control.label)?.trim() ? t('common.required', 'Required') : undefined,
    } : { label: undefined };

    const controlValidations = requestControlsValidations.filter(v => v.activityControlId === control.id);
    const controlTransitions = transitions.filter(tr => tr.activityControlId === control.id);

    const isClosedControl = [
        'dropdown', 'dropdownlist', 'combobox', 'dropdown-manual',
        'checkbox', 'checkboxlist', 'radiobuttonlist',
    ].includes(control.type);



    const handleSaveAll = async () => {
        setShowErrors(true);
        const labelOk = !!(isRtl ? control.labelAR : control.label)?.trim();
        if (!control.code || !labelOk) return;
        setSaving(true);
        try {
            await saveActivityToBackend(stepId, activity);
        } finally {
            setSaving(false);
        }
    };

    const addTransitionForControl = () => {
        const newTr: Transition = {
            id: uid(),
            activityId,
            activityControlId: control.id,
            variableId: '',
            operatorId: '',
            value: '',
            stepId: '',
            isActive: true,
            sortOrder: (transitions.length + 1) * 10,
            dirty: true,
        };
        setTransitions((prev) => [...prev, newTr]);
    };

    return (
        <Stack spacing={2} sx={{ p: 2 }}>
            <Stack direction="row" alignItems="center" spacing={1}>
                <Typography variant="h6" sx={{ flexGrow: 1, fontWeight: 700 }}>
                    {t('workflow.control_settings', 'Control Settings')}
                </Typography>
                {control.serverId
                    ? <Chip size="small" color="success" label={`ID: ${control.serverId}`} sx={{ borderRadius: 1.5, fontWeight: 600 }} />
                    : <Chip size="small" label={t('common.new', 'New')} sx={{ borderRadius: 1.5, fontWeight: 600 }} />}
                {control.dirty && <Chip size="small" color="warning" label={t('common.unsaved', 'unsaved')} sx={{ borderRadius: 1.5, fontWeight: 600 }} />}
            </Stack>

            {/* Code */}
            <GeneratableTextField
                label={t('common.code')}
                value={control.code ?? ''}
                onChange={(val) => updateControl(stepId, activityId, control.id, { code: val })}
                sequenceType="WfActivityControl"
                required
                error={!control.code}
                helperText={!control.code ? t('common.required', 'Required') : undefined}
                disabled={!!control.serverId}
            />

            <BilingualField
                labelEN={t('common.label')}
                labelAR={t('workflow.label_ar')}
                nameValue={control.label}
                nameARValue={control.labelAR}
                onChange={(label, labelAR) => updateControl(stepId, activityId, control.id, { label, labelAR })}
                required
                error={!!errors.label}
                errorMessage={errors.label}
            />

            {/* Variable Binding */}
            <FormControl size="small" sx={{ '& .MuiOutlinedInput-root': { borderRadius: 1.5 } }}>
                <InputLabel>{t('workflow.variable_binding', 'Variable Binding')}</InputLabel>
                <Select
                    label={t('workflow.variable_binding', 'Variable Binding')}
                    value={control.bindVariableId ?? ''}
                    onChange={(e) => {
                        const val = e.target.value;
                        const updates: Partial<typeof control> = { bindVariableId: val || undefined };
                        if (val) {
                            const v = variables.find(x => x.id === val);
                            if (v) {
                                if (!control.label) updates.label = v.name;
                                if (!control.labelAR && v.nameAR) updates.labelAR = v.nameAR;
                                if (!control.code) updates.code = v.code || `VAR_${v.id}`;
                            }
                        }
                        updateControl(stepId, activityId, control.id, updates);
                    }}
                >
                    <MenuItem value=""><em>({t('common.none', 'none')})</em></MenuItem>
                    {variables.map((v) =>
                        <MenuItem key={v.id} value={v.id}>{v.name} · {v.dataType}</MenuItem>
                    )}
                </Select>
            </FormControl>

            {/* Options for dropdown / multi-select control types (mirrors the Request Control panel).
                These map to optionsX, which the control mapper serializes into ExtendedProperties XML. */}
            {(control.type === 'dropdown' || control.type === 'dropdown-manual'
                || control.type === 'checkboxlist' || control.type === 'radiobuttonlist') && (
                <Box>
                    <Stack direction="row" alignItems="center" sx={{ mb: 1 }}>
                        <Typography variant="subtitle2" sx={{ flexGrow: 1 }}>
                            {t('workflow.options', 'Options')} ({(control.optionsX ?? []).length})
                        </Typography>
                        <Button size="small" startIcon={<Add />}
                            onClick={() => updateControl(stepId, activityId, control.id, {
                                optionsX: [...(control.optionsX ?? []), { ar: '', en: '', value: '' }]
                            })}>{t('workflow.add_option', 'Add Option')}</Button>
                    </Stack>
                    <Stack spacing={0.5}>
                        {(control.optionsX ?? []).map((opt, idx) => (
                            <Stack key={idx} direction="row" spacing={0.5} alignItems="center">
                                <TextField size="small" placeholder="ar" dir="rtl" value={opt.ar} sx={{ flex: 1 }}
                                    onChange={(e) => {
                                        const next = [...(control.optionsX ?? [])];
                                        next[idx] = { ...next[idx], ar: e.target.value };
                                        updateControl(stepId, activityId, control.id, { optionsX: next });
                                    }} />
                                <TextField size="small" placeholder="en" value={opt.en} sx={{ flex: 1 }}
                                    onChange={(e) => {
                                        const next = [...(control.optionsX ?? [])];
                                        next[idx] = { ...next[idx], en: e.target.value };
                                        updateControl(stepId, activityId, control.id, { optionsX: next });
                                    }} />
                                <TextField size="small" placeholder="value" value={opt.value} sx={{ flex: 1 }}
                                    onChange={(e) => {
                                        const next = [...(control.optionsX ?? [])];
                                        next[idx] = { ...next[idx], value: e.target.value };
                                        updateControl(stepId, activityId, control.id, { optionsX: next });
                                    }} />
                                <IconButton size="small" color="error"
                                    onClick={() => updateControl(stepId, activityId, control.id, {
                                        optionsX: (control.optionsX ?? []).filter((_, i) => i !== idx)
                                    })}>
                                    <Delete fontSize="small" />
                                </IconButton>
                            </Stack>
                        ))}
                        {(control.optionsX ?? []).length === 0 && (
                            <Typography variant="caption" color="text.secondary">
                                {t('workflow.no_options_yet', 'No options yet — click "Add Option".')}
                            </Typography>
                        )}
                    </Stack>
                </Box>
            )}

            {/* Toggles */}
            <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', columnGap: 2, rowGap: 1, border: '1px solid', borderColor: 'divider', borderRadius: 2, p: 1.5 }}>
                <FormControlLabel
                    sx={{ m: 0, justifyContent: 'space-between', display: 'flex' }}
                    labelPlacement="start"
                    control={<Switch size="small" checked={control.required} onChange={(e) => updateControl(stepId, activityId, control.id, { required: e.target.checked })} />}
                    label={<Typography variant="body2" sx={{ fontWeight: 500 }}>{t('common.required', 'Required')}</Typography>}
                />
                <FormControlLabel
                    sx={{ m: 0, justifyContent: 'space-between', display: 'flex' }}
                    labelPlacement="start"
                    control={<Switch size="small" checked={control.readOnly} onChange={(e) => updateControl(stepId, activityId, control.id, { readOnly: e.target.checked })} />}
                    label={<Typography variant="body2" sx={{ fontWeight: 500 }}>{t('common.read_only', 'ReadOnly')}</Typography>}
                />
                <FormControlLabel
                    sx={{ m: 0, justifyContent: 'space-between', display: 'flex' }}
                    labelPlacement="start"
                    control={<Switch size="small" checked={control.visible} onChange={(e) => updateControl(stepId, activityId, control.id, { visible: e.target.checked })} />}
                    label={<Typography variant="body2" sx={{ fontWeight: 500 }}>{t('common.visible', 'Visible')}</Typography>}
                />
            </Box>

            {/* Save Button */}
            <Button
                variant="contained"
                startIcon={<AccountTree />}
                disabled={!processInfo.id || saving}
                onClick={handleSaveAll}
                sx={{ borderRadius: 1.5, py: 1, textTransform: 'none', fontWeight: 600 }}
            >
                {saving
                    ? t('common.saving', 'Saving…')
                    : control.serverId ? t('workflow.update_control', 'Update Control') : t('workflow.create_control', 'Create Control')}
            </Button>

            <Divider />

            {/* ── Validation Rules ─────────────────────────────────────────── */}
            <Stack direction="row" alignItems="center">
                <Typography variant="subtitle2" sx={{ flexGrow: 1, fontWeight: 700 }}>
                    {t('workflow.validation_rules', 'Validation Rules')}
                </Typography>
                <Button
                    size="small"
                    startIcon={<Add />}
                    onClick={() => addActivityControlsValidation(control.id)}
                    sx={{ textTransform: 'none' }}
                >
                    {t('common.add', 'Add')}
                </Button>
            </Stack>
            <Stack spacing={2}>
                {controlValidations.map((v) => {
                    const isCustomExpr = v.validationType === 'CustomExpression';
                    const exprHint = EXPRESSION_HINTS[v.validationType];

                    const handleFieldChange = (patch: Partial<typeof v>) => {
                        const nextType = patch.validationType !== undefined ? patch.validationType : v.validationType;
                        const nextExpr = patch.validationExpression !== undefined ? patch.validationExpression : (v.validationExpression || '');

                        const finalPatch = { ...patch };

                        if (patch.validationType !== undefined && patch.validationType !== v.validationType) {
                            const matchedPattern = MASK_PATTERNS.find(p => p.validationType === patch.validationType && p.regex);
                            finalPatch.validationExpression = matchedPattern?.regex ?? '';
                            if (VALIDATION_TYPE_TO_MASK[patch.validationType]) {
                                updateControl(stepId, activityId, control.id, { mask: VALIDATION_TYPE_TO_MASK[patch.validationType] });
                            }
                        }

                        if (nextType !== 'CustomExpression') {
                            let val1 = finalPatch.validationExpression ?? nextExpr;
                            let computedVal2 = v.maskInput || '';
                            if (nextType === 'Range') {
                                const parts = val1.split('-');
                                val1 = parts[0] || '';
                                computedVal2 = parts[1] || '';
                            } else if (nextType === 'DateRange') {
                                const parts = val1.split('|');
                                val1 = parts[0] || '';
                                computedVal2 = parts[1] || '';
                            }
                            const msg = getAutoGeneratedMessage(nextType, val1, computedVal2);
                            finalPatch.errorMessageAr = msg.ar;
                            finalPatch.errorMessageEn = msg.en;
                        }
                        updateRequestControlsValidation(v.id, finalPatch);
                    };

                    return (
                        <Paper key={v.id} variant="outlined" sx={{ p: 2, borderRadius: 1.5 }}>
                            <Stack spacing={1.5}>
                                {/* Validation Type & Severity */}
                                <Stack direction="row" spacing={1}>
                                    <FormControl size="small" sx={{ flex: 1.2 }}>
                                        <InputLabel>{t('workflow.validation_type', 'Validation Type')}</InputLabel>
                                        <Select
                                            label={t('workflow.validation_type', 'Validation Type')}
                                            value={v.validationType || 'Required'}
                                            onChange={(e) => handleFieldChange({ validationType: e.target.value })}
                                        >
                                            {getValidationTypesForControl(control.type).map((vt) => (
                                                <MenuItem key={vt} value={vt}>{vt}</MenuItem>
                                            ))}
                                        </Select>
                                    </FormControl>
                                    <FormControl size="small" sx={{ flex: 0.8 }}>
                                        <InputLabel>{t('workflow.severity', 'Severity')}</InputLabel>
                                        <Select
                                            label={t('workflow.severity', 'Severity')}
                                            value={v.severity || 'Error'}
                                            onChange={(e) => updateRequestControlsValidation(v.id, { severity: e.target.value })}
                                        >
                                            {['Error', 'Warning', 'Information'].map((sv) => (
                                                <MenuItem key={sv} value={sv}>{sv}</MenuItem>
                                            ))}
                                        </Select>
                                    </FormControl>
                                </Stack>

                                {/* Expression / Rule Value */}
                                {exprHint && (
                                    <TextField
                                        size="small"
                                        fullWidth
                                        label={t('workflow.validation_expression', 'Expression / Rule Value')}
                                        value={v.validationExpression || ''}
                                        placeholder={exprHint.placeholder}
                                        helperText={exprHint.hint}
                                        FormHelperTextProps={{ sx: { mx: 0, mt: 0.5, fontSize: '0.72rem' } }}
                                        onChange={(e) => handleFieldChange({ validationExpression: e.target.value })}
                                    />
                                )}

                                {/* Input Mask for format-based types */}
                                {MASK_TYPES.has(v.validationType) && (() => {
                                    const relevantPresets = MASK_PATTERNS.filter(p => p.validationType === v.validationType);
                                    return (
                                        <Stack spacing={0.5}>
                                            <TextField
                                                size="small"
                                                fullWidth
                                                label={t('workflow.input_mask', 'Input Mask')}
                                                value={control.mask ?? ''}
                                                placeholder={VALIDATION_TYPE_TO_MASK[v.validationType] ?? 'e.g. 000-000-0000'}
                                                helperText={t('workflow.input_mask_hint', '0 = digit · a = letter · * = any')}
                                                FormHelperTextProps={{ sx: { mx: 0, mt: 0.5, fontSize: '0.72rem' } }}
                                                onChange={(e) => updateControl(stepId, activityId, control.id, { mask: e.target.value || undefined })}
                                            />
                                            {relevantPresets.length > 0 && (
                                                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                                                    {relevantPresets.map((p) => (
                                                        <Chip
                                                            key={p.label}
                                                            label={p.label}
                                                            size="small"
                                                            variant={control.mask === p.mask ? 'filled' : 'outlined'}
                                                            color={control.mask === p.mask ? 'primary' : 'default'}
                                                            onClick={() => updateControl(stepId, activityId, control.id, { mask: p.mask })}
                                                            sx={{ fontSize: '0.7rem', height: 22, cursor: 'pointer' }}
                                                        />
                                                    ))}
                                                    {control.mask && (
                                                        <Chip
                                                            label={t('common.clear', 'Clear')}
                                                            size="small"
                                                            variant="outlined"
                                                            color="error"
                                                            onClick={() => updateControl(stepId, activityId, control.id, { mask: undefined })}
                                                            sx={{ fontSize: '0.7rem', height: 22, cursor: 'pointer' }}
                                                        />
                                                    )}
                                                </Box>
                                            )}
                                        </Stack>
                                    );
                                })()}

                                {/* CustomExpression: Operator + Value */}
                                {isCustomExpr && (
                                    <Stack direction="row" spacing={1}>
                                        <FormControl size="small" sx={{ flex: 1 }}>
                                            <InputLabel>{t('workflow.operator', 'Operator')}</InputLabel>
                                            <Select
                                                label={t('workflow.operator', 'Operator')}
                                                value={v.operator || ''}
                                                onChange={(e) => handleFieldChange({ operator: e.target.value })}
                                            >
                                                <MenuItem value=""><em>({t('common.none', 'none')})</em></MenuItem>
                                                {['=', '==', '!=', '>', '<', '>=', '<=', 'contains', 'isEmpty'].map((op) => (
                                                    <MenuItem key={op} value={op}>{op}</MenuItem>
                                                ))}
                                            </Select>
                                        </FormControl>
                                        <TextField
                                            size="small"
                                            label={t('common.value', 'Value')}
                                            value={v.value || ''}
                                            fullWidth
                                            sx={{ flex: 1 }}
                                            onChange={(e) => handleFieldChange({ value: e.target.value })}
                                        />
                                    </Stack>
                                )}

                                {/* Error Messages (editable for CustomExpression) */}
                                {isCustomExpr && (
                                    <Stack spacing={1}>
                                        <TextField
                                            size="small"
                                            fullWidth
                                            label={t('workflow.err_msg_en', 'Error Message (EN)')}
                                            value={v.errorMessageEn || ''}
                                            onChange={(e) => updateRequestControlsValidation(v.id, { errorMessageEn: e.target.value })}
                                        />
                                        <TextField
                                            size="small"
                                            fullWidth
                                            label={t('workflow.err_msg_ar', 'Error Message (AR)')}
                                            value={v.errorMessageAr || ''}
                                            dir="rtl"
                                            onChange={(e) => updateRequestControlsValidation(v.id, { errorMessageAr: e.target.value })}
                                        />
                                    </Stack>
                                )}

                                {/* Active & Delete */}
                                <Stack direction="row" alignItems="center" justifyContent="space-between">
                                    <FormControlLabel
                                        control={
                                            <Switch
                                                size="small"
                                                checked={v.isActive}
                                                onChange={(e) => updateRequestControlsValidation(v.id, { isActive: e.target.checked })}
                                            />
                                        }
                                        label={t('common.active', 'Active')}
                                    />
                                    <IconButton size="small" color="error" onClick={() => deleteRequestControlsValidation(v.id)}>
                                        <Delete fontSize="small" />
                                    </IconButton>
                                </Stack>
                            </Stack>
                        </Paper>
                    );
                })}
                {controlValidations.length === 0 && (
                    <Typography variant="caption" color="text.secondary" align="center">
                        {t('workflow.no_validations_yet', 'No validation rules yet.')}
                    </Typography>
                )}
            </Stack>

            <Divider />

            {/* ── Transitions ──────────────────────────────────────────────── */}
            <Stack direction="row" alignItems="center">
                <Typography variant="subtitle2" sx={{ flexGrow: 1, fontWeight: 700 }}>
                    {t('workflow.transitions', 'Transitions')} ({controlTransitions.length})
                </Typography>
                <Button size="small" startIcon={<Add />} onClick={addTransitionForControl} sx={{ textTransform: 'none' }}>
                    {t('common.add', 'Add')}
                </Button>
            </Stack>
            <Stack spacing={1.5}>
                {controlTransitions.map((tr) => (
                    <Paper key={tr.id} variant="outlined" sx={{ p: 1.5, borderRadius: 1.5 }} onClick={(e) => e.stopPropagation()}>
                        <Stack spacing={1}>
                            {/* Variable & Operator */}
                            <Stack direction="row" spacing={1}>
                                <FormControl size="small" sx={{ flex: 1 }} onClick={(e) => e.stopPropagation()}>
                                    <InputLabel>{t('workflow.variable', 'Variable')}</InputLabel>
                                    <Select
                                        label={t('workflow.variable', 'Variable')}
                                        value={tr.variableId || ''}
                                        onChange={(e) => updateTransition(tr.id, { variableId: e.target.value })}
                                    >
                                        <MenuItem value="">—</MenuItem>
                                        {variables.map((v) => (
                                            <MenuItem key={v.id} value={v.id}>
                                                {v.code ? `${v.code} - ` : ''}{isRtl ? v.nameAR || v.name : v.name}
                                            </MenuItem>
                                        ))}
                                    </Select>
                                </FormControl>

                                <FormControl size="small" sx={{ flex: 1 }} onClick={(e) => e.stopPropagation()}>
                                    <InputLabel>{t('workflow.operator', 'Operator')}</InputLabel>
                                    <Select
                                        label={t('workflow.operator', 'Operator')}
                                        value={tr.operatorId || ''}
                                        onChange={(e) => updateTransition(tr.id, { operatorId: e.target.value as number })}
                                    >
                                        <MenuItem value="">—</MenuItem>
                                        {operators.map((op) => (
                                            <MenuItem key={op.id} value={op.id}>
                                                {isRtl ? op.nameAR || op.name : op.name}
                                            </MenuItem>
                                        ))}
                                    </Select>
                                </FormControl>
                            </Stack>

                            {/* Value & Target Step */}
                            <Stack direction="row" spacing={1} alignItems="center">
                                <Box sx={{ flex: 1 }} onClick={(e) => e.stopPropagation()}>
                                    {isClosedControl ? (
                                        <FormControl size="small" fullWidth onClick={(e) => e.stopPropagation()}>
                                            <InputLabel>{t('common.value', 'Value')}</InputLabel>
                                            <Select
                                                label={t('common.value', 'Value')}
                                                value={tr.value || ''}
                                                onChange={(e) => updateTransition(tr.id, { value: e.target.value as string })}
                                            >
                                                <MenuItem value="">—</MenuItem>
                                                {control.type === 'checkbox' ? [
                                                    <MenuItem key="true" value="true">{t('common.yes', 'Yes')}</MenuItem>,
                                                    <MenuItem key="false" value="false">{t('common.no', 'No')}</MenuItem>,
                                                ] : (
                                                    (control.optionsX || []).map((opt, idx) => (
                                                        <MenuItem key={idx} value={opt.value}>
                                                            {isRtl ? opt.ar || opt.en || opt.value : opt.en || opt.ar || opt.value}
                                                        </MenuItem>
                                                    ))
                                                )}
                                            </Select>
                                        </FormControl>
                                    ) : (
                                        <TextField
                                            size="small"
                                            fullWidth
                                            label={t('common.value', 'Value')}
                                            value={tr.value || ''}
                                            onClick={(e) => e.stopPropagation()}
                                            onChange={(e) => updateTransition(tr.id, { value: e.target.value })}
                                        />
                                    )}
                                </Box>

                                <FormControl size="small" sx={{ flex: 1 }} onClick={(e) => e.stopPropagation()}>
                                    <InputLabel>{t('workflow.target_step', 'Target Step')}</InputLabel>
                                    <Select
                                        label={t('workflow.target_step', 'Target Step')}
                                        value={tr.stepId || ''}
                                        onChange={(e) => updateTransition(tr.id, { stepId: e.target.value })}
                                    >
                                        <MenuItem value="">—</MenuItem>
                                        {steps.map((s) => (
                                            <MenuItem key={s.id} value={s.id}>
                                                {isRtl ? s.nameAR || s.name : s.name}
                                            </MenuItem>
                                        ))}
                                    </Select>
                                </FormControl>
                            </Stack>

                            {/* Active & Delete */}
                            <Stack direction="row" alignItems="center" justifyContent="space-between" onClick={(e) => e.stopPropagation()}>
                                <FormControlLabel
                                    control={
                                        <Switch
                                            size="small"
                                            checked={tr.isActive}
                                            onChange={(e) => updateTransition(tr.id, { isActive: e.target.checked })}
                                        />
                                    }
                                    label={t('common.active', 'Active')}
                                />
                                <IconButton
                                    size="small"
                                    color="error"
                                    onClick={(e) => {
                                        e.stopPropagation();
                                        deleteTransition(tr.id);
                                    }}
                                >
                                    <Delete fontSize="small" />
                                </IconButton>
                            </Stack>
                        </Stack>
                    </Paper>
                ))}
                {controlTransitions.length === 0 && (
                    <Typography variant="caption" color="text.secondary" align="center">
                        {t('workflow.no_transitions_yet', 'No transitions yet.')}
                    </Typography>
                )}
            </Stack>

            <Divider />

            {/* ── Visibility Rule ───────────────────────────────────────────── */}
            <Accordion variant="outlined" sx={{ borderRadius: '2px !important', overflow: 'hidden' }}>
                <AccordionSummary expandIcon={<ExpandMore />}>
                    <Typography variant="subtitle2" sx={{ fontWeight: 600 }}>
                        {t('workflow.visibility_rule', 'Visibility Rule')}
                    </Typography>
                </AccordionSummary>
                <AccordionDetails sx={{ p: 1.5 }}>
                    <ConditionBuilder
                        group={control.visibilityRule}
                        onChange={(g) => updateControl(stepId, activityId, control.id, { visibilityRule: g })}
                        fields={allFieldNames}
                    />
                </AccordionDetails>
            </Accordion>
        </Stack>
    );
});

ActivityControlSettingsPanel.displayName = 'ActivityControlSettingsPanel';
