import React, { useState } from 'react';
import {
    Stack, Box, Typography, Chip, TextField, FormControlLabel, Switch,
    FormControl, InputLabel, Select, MenuItem, Button, Divider, Paper, IconButton
} from '@mui/material';
import { useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Add, Delete, AccountTree } from '@mui/icons-material';
import { notify } from '../../../../../../lib/notify';
import type { ControlType, Transition } from '../../types';
import { CONTROL_PALETTE } from '../../utils/palette';
import { uid } from '../../utils/uid';
import { DynamicField } from '../../../../../../components/common/DynamicField';
import { BilingualField } from '../../../../../../components/common/BilingualField';
import { GeneratableTextField } from '../../../../../../components/common/GeneratableTextField';
import { useProcessBuilderContext } from '../../context/ProcessBuilderContext';
import { useProcessBuilderData } from '../../hooks/useProcessBuilderData';
import { getAutoGeneratedMessage, getValidationTypesForControl } from '../../../../utils/validationHelper';

// =========================================================================
// Structural mask patterns — common presets a user can click to apply
// Syntax: 0 = digit, a = letter, * = any character
// validationType: links this mask to a validation rule type (auto-creates rule on click)
// regex: the server-side validation expression that enforces the mask's structure
// =========================================================================
interface MaskPattern { label: string; mask: string; validationType?: string; regex?: string; }

const MASK_PATTERNS: MaskPattern[] = [
    { label: 'Phone (US)',       mask: '000-000-0000',                     validationType: 'Phone',            regex: '^\\d{3}-\\d{3}-\\d{4}$' },
    { label: 'Phone (Intl)',     mask: '+000 000 000 0000',                validationType: 'Phone',            regex: '^\\+\\d{1,3} \\d{3} \\d{3} \\d{4}$' },
    { label: 'Mobile (SA)',      mask: '+966 00 000 0000',                 validationType: 'Mobile',           regex: '^\\+966 \\d{2} \\d{3} \\d{4}$' },
    { label: 'National ID (SA)', mask: '0000000000',                       validationType: 'NationalID',       regex: '^\\d{10}$' },
    { label: 'IBAN (SA)',        mask: 'SA00 0000 0000 0000 0000 0000',    validationType: 'IBAN',             regex: '^SA\\d{22}$' },
    { label: 'Credit Card',      mask: '0000 0000 0000 0000',              validationType: 'CreditCardFormat', regex: '^\\d{16}$' },
    { label: 'Passport (SA)',    mask: 'a0000000',                         validationType: 'PassportNumber',   regex: '^[A-Z]{1}\\d{7}$' },
    { label: 'Tax Number (SA)',  mask: '000000000000000',                  validationType: 'TaxNumber',        regex: '^\\d{15}$' },
    { label: 'SSN',              mask: '000-00-0000',                      validationType: 'Regex',            regex: '^\\d{3}-\\d{2}-\\d{4}$' },
    { label: 'Date MM/DD/YYYY',  mask: '00/00/0000' },
    { label: 'Date DD-MM-YYYY',  mask: '00-00-0000' },
    { label: 'Time HH:MM',       mask: '00:00' },
    { label: 'Time HH:MM:SS',    mask: '00:00:00' },
    { label: 'Postal Code (US)', mask: '00000-0000' },
    { label: 'ZIP (SA)',         mask: '00000-0000' },
    { label: 'CVV',              mask: '000' },
    { label: 'IP Address',       mask: '000.000.000.000' },
    { label: 'MAC Address',      mask: 'XX:XX:XX:XX:XX:XX' },
    { label: 'Percentage',       mask: '000%' },
    { label: 'Currency (2 dec)', mask: '000,000,000.00' },
];

// Reverse lookup: validationType → mask (for auto-populating mask when validation type is selected)
const VALIDATION_TYPE_TO_MASK: Record<string, string> = Object.fromEntries(
    MASK_PATTERNS
        .filter((p): p is MaskPattern & { validationType: string } => !!p.validationType && p.validationType !== 'Regex')
        .map((p) => [p.validationType, p.mask])
);

// Set of validation types that show the mask input field inside the rule card
const MASK_TYPES = new Set([...Object.keys(VALIDATION_TYPE_TO_MASK), 'Regex']);

// =========================================================================
// Expression hint data — drives placeholder + helper text per ValidationType
// Types absent from this map do not require an expression value.
// =========================================================================
interface ExpressionHint { placeholder: string; hint: string; }

const EXPRESSION_HINTS: Record<string, ExpressionHint> = {
    // ── Text / String ──────────────────────────────────────────────────────
    MinLength:          { placeholder: 'e.g. 5',                            hint: 'Minimum number of characters required' },
    MaxLength:          { placeholder: 'e.g. 255',                          hint: 'Maximum number of characters allowed' },
    ExactLength:        { placeholder: 'e.g. 10',                           hint: 'Field must contain exactly this many characters' },
    Regex:              { placeholder: 'e.g. ^[A-Z]{3}[0-9]+$',            hint: 'Regular expression pattern the value must fully match' },
    StartsWith:         { placeholder: 'e.g. INV-',                         hint: 'Value must begin with this prefix' },
    EndsWith:           { placeholder: 'e.g. .pdf',                         hint: 'Value must end with this suffix' },
    Contains:           { placeholder: 'e.g. @company.com',                 hint: 'Value must include this exact substring' },
    DoesNotContain:     { placeholder: 'e.g. admin',                        hint: 'Value must NOT include this substring' },
    AllowedValues:      { placeholder: 'e.g. active,inactive,pending',      hint: 'Comma-separated list of the only permitted values' },
    ForbiddenValues:    { placeholder: 'e.g. null,undefined,N/A',           hint: 'Comma-separated list of disallowed values' },
    // ── Number ─────────────────────────────────────────────────────────────
    MinValue:           { placeholder: 'e.g. 0',                            hint: 'Value must be greater than or equal to this number' },
    MaxValue:           { placeholder: 'e.g. 1000000',                      hint: 'Value must be less than or equal to this number' },
    Range:              { placeholder: 'e.g. 1-100',                        hint: 'Format: min-max  (dash-separated, inclusive)' },
    DecimalPrecision:   { placeholder: 'e.g. 2',                            hint: 'Maximum number of decimal places permitted' },
    // ── Date ───────────────────────────────────────────────────────────────
    DateRange:          { placeholder: 'e.g. 2024-01-01|2024-12-31',        hint: 'Format: startDate|endDate  (ISO 8601, pipe-separated)' },
    MinimumAge:         { placeholder: 'e.g. 18',                           hint: 'Minimum age in full years, calculated from today' },
    MaximumAge:         { placeholder: 'e.g. 65',                           hint: 'Maximum age in full years, calculated from today' },
    // ── Phone / Mobile ─────────────────────────────────────────────────────
    Phone:              { placeholder: 'e.g. ^\\d{3}-\\d{3}-\\d{4}$',       hint: 'Regex pattern the phone number must fully match' },
    Mobile:             { placeholder: 'e.g. ^\\+966\\d{9}$',               hint: 'Regex pattern the mobile number must fully match' },
    // ── Format ─────────────────────────────────────────────────────────────
    NationalID:         { placeholder: 'e.g. ^[0-9]{10}$',                  hint: 'Regex pattern the national ID must fully match' },
    TaxNumber:          { placeholder: 'e.g. ^[0-9]{15}$',                  hint: 'Regex pattern the tax number must fully match' },
    PassportNumber:     { placeholder: 'e.g. ^[A-Z]{1}[0-9]{7}$',          hint: 'Regex pattern the passport number must fully match' },
    IBAN:               { placeholder: 'e.g. ^SA[0-9]{22}$',                hint: 'Regex pattern the IBAN must fully match' },
    CreditCardFormat:   { placeholder: 'e.g. ^[0-9]{16}$',                  hint: 'Regex pattern the credit card number must fully match' },
    // ── File ───────────────────────────────────────────────────────────────
    AllowedExtensions:  { placeholder: 'e.g. .pdf,.xlsx,.docx',             hint: 'Comma-separated list of permitted file extensions (with dot)' },
    BlockedExtensions:  { placeholder: 'e.g. .exe,.bat,.sh',                hint: 'Comma-separated list of blocked file extensions (with dot)' },
    MaxFileSize:        { placeholder: 'e.g. 5',                            hint: 'Maximum allowed file size in megabytes (MB)' },
    MinFileSize:        { placeholder: 'e.g. 0.1',                          hint: 'Minimum required file size in megabytes (MB)' },
    MaxNumberOfFiles:   { placeholder: 'e.g. 3',                            hint: 'Maximum number of files that can be uploaded at once' },
    // ── Selection ──────────────────────────────────────────────────────────
    MinSelectedItems:   { placeholder: 'e.g. 1',                            hint: 'Minimum number of items that must be selected' },
    MaxSelectedItems:   { placeholder: 'e.g. 5',                            hint: 'Maximum number of items that can be selected' },
    ExactSelectedItems: { placeholder: 'e.g. 3',                            hint: 'Exact number of items that must be selected' },
    // ── Expression ─────────────────────────────────────────────────────────
    Expression:         { placeholder: 'e.g. {Amount} > 1000',              hint: 'Boolean expression. Use {field_code} to reference other fields' },
    CrossField:         { placeholder: 'e.g. {EndDate} > {StartDate}',      hint: 'Compare this field against another using {field_code} references' },
    Conditional:        { placeholder: "e.g. {Status} == 'active'",         hint: 'Condition that must be true for this validation to apply' },
    CustomExpression:   { placeholder: 'e.g. {Amount} >= {MinAmount}',      hint: 'Custom boolean expression. Use {field_code} to reference other fields' },
};

// =========================================================================
// RequestControlSettingsPanel (Global Request Control properties settings)
// =========================================================================
export const RequestControlSettingsPanel: React.FC = React.memo(() => {
    const { i18n, t } = useTranslation();
    const isRtl = i18n.language === 'ar';
    const { id: routeId } = useParams<{ id: string }>();
    const isEditMode = !!routeId && routeId !== 'new';

    const {
        variables, updateRequestControl, selectedNode, processInfo, requestControls,
        steps, transitions, setTransitions, updateTransition, deleteTransition, deletedTransitionServerIds,
        requestControlsValidations, addRequestControlsValidation, updateRequestControlsValidation, deleteRequestControlsValidation, deletedRequestControlsValidationServerIds
    } = useProcessBuilderContext();

    const {
        wfControls, requestControlsSaving, saveRequestControlsToBackend, saveTransitionsToBackend, operators
    } = useProcessBuilderData(processInfo.id, isEditMode, true);

    const [showErrors, setShowErrors] = useState(false);

    if (selectedNode.kind !== 'requestControl') return null;
    const control = requestControls.find(c => c.id === selectedNode.id);
    if (!control) return null;

    const errors = showErrors ? {
        label: !(isRtl ? control.labelAR : control.label)?.trim() ? t('common.required', 'Required') : undefined,
    } : { label: undefined };



    const controlTransitions = transitions.filter(
        tr => tr.requestControlId === control.id
    );

    const isClosedControl = [
        'dropdown',
        'dropdownlist',
        'combobox',
        'dropdown-manual',
        'checkbox',
        'checkboxlist',
        'radiobuttonlist'
    ].includes(control.type);

    const addTransitionForControl = () => {
        const newId = uid();
        const t: Transition = {
            id: newId,
            requestControlId: control.id,
            variableId: '',
            operatorId: '',
            value: '',
            stepId: '',
            isActive: true,
            sortOrder: (transitions.length + 1) * 10,
            dirty: true,
        };
        setTransitions((prev) => [...prev, t]);
    };

    const handleSaveAll = async () => {
        setShowErrors(true);
        const labelOk = !!(isRtl ? control.labelAR : control.label)?.trim();
        if (!control.code || !labelOk) return;

        const hasControlChanges = requestControls.some(c => c.dirty);
        // Request flow only — activity-control transitions/validations are saved
        // independently from the Activity Control panel.
        const hasTransitionChanges = transitions.some(t => t.dirty && !t.activityControlId) || (deletedTransitionServerIds && deletedTransitionServerIds.length > 0);
        const hasValidationChanges = requestControlsValidations.some(v => v.dirty && !v.activityControlId) || (deletedRequestControlsValidationServerIds && deletedRequestControlsValidationServerIds.length > 0);

        if (!hasControlChanges && !hasTransitionChanges && !hasValidationChanges) {
            notify.success(t('workflow.no_changes', 'No changes to save'));
            return;
        }

        try {
            if (hasControlChanges || hasValidationChanges) {
                await saveRequestControlsToBackend(wfControls);
            }
            if (hasTransitionChanges) {
                await saveTransitionsToBackend();
            }
        } catch {
            // Error toasts are handled inside the save functions
        }
    };

    const findControlIdByType = (type: ControlType): number | undefined => {
        const catalog = wfControls.find((w) => w.code === type || w.name === type);
        return catalog?.id;
    };

    const resolvedId = control.controlId ?? findControlIdByType(control.type);
    const catalog = wfControls.find((w) => w.id === resolvedId);
    const controlName = catalog?.name
        ?? CONTROL_PALETTE.find((p) => p.type === control.type)?.label
        ?? control.type;

    return (
        <Stack spacing={2} sx={{ p: 2 }}>
            <Stack direction="row" alignItems="center" spacing={1}>
                <Typography variant="h6" sx={{ flexGrow: 1, fontWeight: 700 }}>{t('workflow.request_control', 'Request Control')}</Typography>
                {control.serverId
                    ? <Chip size="small" color="success" label={`ID: ${control.serverId}`} sx={{ borderRadius: 1.5, fontWeight: 600 }} />
                    : <Chip size="small" label={t('common.new', 'New')} sx={{ borderRadius: 1.5, fontWeight: 600 }} />}
                {control.dirty && <Chip size="small" color="warning" label={t('common.unsaved', 'unsaved')} sx={{ borderRadius: 1.5, fontWeight: 600 }} />}
            </Stack>

            <Stack direction="row" alignItems="center" spacing={1} sx={{ flexWrap: 'wrap' }}>
                <Typography variant="caption" color="text.secondary">
                    {t('workflow.process_id', 'ProcessId')}: {processInfo.id ?? t('workflow.save_process_first', '— (save Process first)')}
                </Typography>
                <Box sx={{ flexGrow: 1 }} />
                <Typography variant="caption" color="text.secondary">
                    {t('workflow.control', 'Control')}: <Box component="span" sx={{ color: 'text.primary', fontWeight: 600 }}>
                        {controlName}
                    </Box>
                </Typography>
            </Stack>

            <GeneratableTextField
                label={t('common.code')}
                value={control.code ?? ''}
                onChange={(val) => updateRequestControl(control.id, { code: val })}
                sequenceType="WfRequestControl"
                required
                error={!control.code}
                helperText={!control.code ? t('common.required', 'Required') : undefined}
                disabled={!!control.serverId}
            />

            <BilingualField
                labelEN={t('common.label')}
                labelAR={t('workflow.label_ar')}
                nameValue={control.label}
                nameARValue={control.labelAR}
                onChange={(label, labelAR) => updateRequestControl(control.id, { label, labelAR })}
                required
                error={!!errors.label}
                errorMessage={errors.label}
            />

            <Stack direction="row" spacing={2} sx={{ alignItems: 'stretch' }}>
                <Box sx={{ flex: 1 }}>
                    <DynamicField
                        config={{ name: 'score', label: t('common.score', 'Score'), type: 'number' }}
                        value={control.score ?? 0}
                        onChange={(val) => updateRequestControl(control.id, { score: Number(val) || 0 })}
                    />
                </Box>

                <Box sx={{
                    flex: 1,
                    display: 'flex',
                    alignItems: 'center',
                    p: 1.5,
                    bgcolor: 'background.paper',
                }}>
                    <FormControlLabel
                        sx={{ m: 0, width: '100%', justifyContent: 'space-between', display: 'flex' }}
                        labelPlacement="start"
                        control={<Switch size="small" checked={control.visible}
                            onChange={(e) => updateRequestControl(control.id, { visible: e.target.checked })}
                            sx={{
                                '& .MuiSwitch-switchBase.Mui-checked': { color: '#6366f1' },
                                '& .MuiSwitch-switchBase.Mui-checked + .MuiSwitch-track': { bgcolor: '#6366f1' }
                            }} />}
                        label={<Typography variant="body2" sx={{ fontWeight: 500 }}>{t('common.active', 'Active')}</Typography>} />
                </Box>
            </Stack>



            {(control.type === 'dropdown' || control.type === 'dropdown-manual'
                || control.type === 'checkboxlist' || control.type === 'radiobuttonlist') && (
                    <Box>
                        <Stack direction="row" alignItems="center" sx={{ mb: 1 }}>
                            <Typography variant="subtitle2" sx={{ flexGrow: 1 }}>
                                {t('workflow.options', 'Options')} ({(control.optionsX ?? []).length})
                            </Typography>
                            <Button size="small" startIcon={<Add />}
                                onClick={() => updateRequestControl(control.id, {
                                    optionsX: [...(control.optionsX ?? []), { ar: '', en: '', value: '' }]
                                })}>{t('workflow.add_option', 'Add Option')}</Button>
                        </Stack>
                        <Stack spacing={0.5}>
                            {(control.optionsX ?? []).map((opt, idx) => (
                                <Stack key={idx} direction="row" spacing={0.5} alignItems="center">
                                    <TextField size="small" placeholder="ar" dir="rtl" value={opt.ar} sx={{ flex: 1 }}
                                        onChange={(e) => {
                                            const next = [...(control.optionsX ?? [])];
                                            next[idx] = { ...next[idx], ar: e.target.value };
                                            updateRequestControl(control.id, { optionsX: next });
                                        }} />
                                    <TextField size="small" placeholder="en" value={opt.en} sx={{ flex: 1 }}
                                        onChange={(e) => {
                                            const next = [...(control.optionsX ?? [])];
                                            next[idx] = { ...next[idx], en: e.target.value };
                                            updateRequestControl(control.id, { optionsX: next });
                                        }} />
                                    <TextField size="small" placeholder="value" value={opt.value} sx={{ flex: 1 }}
                                        onChange={(e) => {
                                            const next = [...(control.optionsX ?? [])];
                                            next[idx] = { ...next[idx], value: e.target.value };
                                            updateRequestControl(control.id, { optionsX: next });
                                        }} />
                                    <IconButton size="small" color="error"
                                        onClick={() => updateRequestControl(control.id, {
                                            optionsX: (control.optionsX ?? []).filter((_, i) => i !== idx)
                                        })}>
                                        <Delete fontSize="small" />
                                    </IconButton>
                                </Stack>
                            ))}
                            {(control.optionsX ?? []).length === 0 && (
                                <Typography variant="caption" color="text.secondary">
                                    {t('workflow.no_options_yet', 'No options yet — click "Add Option".')}
                                </Typography>
                            )}
                        </Stack>
                    </Box>
                )}

            {(control.type === 'grid' || control.type === 'table') && (() => {
                const rows = control.gridRows ?? [];
                const colCount = rows.reduce((m, r) => Math.max(m, r.length), 1);
                const setRows = (r: string[][]) => updateRequestControl(control.id, { gridRows: r });
                return (
                    <Box>
                        <Stack direction="row" alignItems="center" sx={{ mb: 1 }}>
                            <Typography variant="subtitle2" sx={{ flexGrow: 1 }}>
                                {t('workflow.grid', 'Grid')} ({rows.length}×{colCount}) — {t('workflow.stored_as_xml', 'stored as <Root> XML')}
                            </Typography>
                            <Button size="small" startIcon={<Add />}
                                onClick={() => setRows([...rows, Array(colCount).fill('')])}>
                                {t('workflow.add_row', 'Add Row')}
                            </Button>
                            <Button size="small" startIcon={<Add />}
                                onClick={() => setRows(rows.map((r) => [...r, '']))}>
                                {t('workflow.add_col', 'Add Col')}
                            </Button>
                        </Stack>
                        <Stack spacing={0.5}>
                            {rows.map((row, ri) => (
                                <Stack key={ri} direction="row" spacing={0.5}>
                                    {Array.from({ length: colCount }, (_, ci) => (
                                        <TextField key={ci} size="small" placeholder={`col${ci + 1}`}
                                            value={row[ci] ?? ''} sx={{ flex: 1 }}
                                            onChange={(e) => {
                                                const next = rows.map((r) => [...r]);
                                                while (next[ri].length < colCount) next[ri].push('');
                                                next[ri][ci] = e.target.value;
                                                setRows(next);
                                            }} />
                                    ))}
                                    <IconButton size="small" color="error"
                                        onClick={() => setRows(rows.filter((_, i) => i !== ri))}>
                                        <Delete fontSize="small" />
                                    </IconButton>
                                </Stack>
                            ))}
                        </Stack>
                    </Box>
                );
            })()}

            {control.type === 'color' && (
                <Stack direction="row" spacing={1} alignItems="center">
                    <Typography variant="subtitle2" sx={{ flexGrow: 1 }}>
                        {t('workflow.color', 'Color')} — {t('workflow.stored_as_hex', 'stored as hex')}
                    </Typography>
                    <input type="color" value={control.color ?? '#ff0000'}
                        onChange={(e) => updateRequestControl(control.id, { color: e.target.value })}
                        style={{ width: 48, height: 36, border: 'none', background: 'none' }} />
                    <TextField size="small" value={control.color ?? '#ff0000'} sx={{ width: 110 }}
                        onChange={(e) => updateRequestControl(control.id, { color: e.target.value })} />
                </Stack>
            )}

            <Button variant="contained" startIcon={<AccountTree />}
                disabled={!processInfo.id || requestControlsSaving}
                onClick={handleSaveAll}
                sx={{ borderRadius: 1.5, py: 1, textTransform: 'none', fontWeight: 600 }}>
                {requestControlsSaving
                    ? t('common.saving', 'Saving…')
                    : control.serverId ? t('workflow.update_req_control', 'Update Request Control') : t('workflow.create_req_control', 'Create Request Control')}
            </Button>

            <Divider />
            <Stack direction="row" alignItems="center">
                <Typography variant="subtitle2" sx={{ flexGrow: 1, fontWeight: 700 }}>
                    {t('workflow.validation_rules', 'Validation Rules')}
                </Typography>
                <Button size="small" startIcon={<Add />} onClick={() => addRequestControlsValidation(control.id)} sx={{ textTransform: 'none' }}>
                    {t('common.add', 'Add')}
                </Button>
            </Stack>
            <Stack spacing={2}>
                {requestControlsValidations
                    .filter((v) => v.requestControlId === control.id)
                    .map((v) => {
                        const isCustomExpr = v.validationType === 'CustomExpression';
                        const exprHint = EXPRESSION_HINTS[v.validationType];

                        const handleFieldChange = (patch: Partial<typeof v>) => {
                            const nextType = patch.validationType !== undefined ? patch.validationType : v.validationType;
                            const nextExpr = patch.validationExpression !== undefined ? patch.validationExpression : (v.validationExpression || '');
                            const nextVal2 = patch.maskInput !== undefined ? patch.maskInput : (v.maskInput || '');

                            const finalPatch = { ...patch };

                            // On type change: clear old values, then auto-fill with the new type's known defaults
                            if (patch.validationType !== undefined && patch.validationType !== v.validationType) {
                                const matchedPattern = MASK_PATTERNS.find(
                                    (p) => p.validationType === patch.validationType && p.regex
                                );
                                finalPatch.validationExpression = matchedPattern?.regex ?? '';
                                updateRequestControl(control.id, { mask: VALIDATION_TYPE_TO_MASK[patch.validationType] ?? undefined });
                            }

                            if (nextType !== 'CustomExpression') {
                                let val1 = finalPatch.validationExpression ?? nextExpr;
                                let computedVal2 = nextVal2;
                                if (nextType === 'Range') {
                                    const parts = val1.split('-');
                                    val1 = parts[0] || '';
                                    computedVal2 = parts[1] || '';
                                } else if (nextType === 'DateRange') {
                                    const parts = val1.split('|');
                                    val1 = parts[0] || '';
                                    computedVal2 = parts[1] || '';
                                }
                                const msg = getAutoGeneratedMessage(nextType, val1, computedVal2);
                                finalPatch.errorMessageAr = msg.ar;
                                finalPatch.errorMessageEn = msg.en;
                            }
                            updateRequestControlsValidation(v.id, finalPatch);
                        };

                        return (
                            <Paper key={v.id} variant="outlined" sx={{ p: 2, borderRadius: 1.5 }}>
                                <Stack spacing={1.5}>
                                    {/* Row 1: ValidationType & Severity */}
                                    <Stack direction="row" spacing={1}>
                                        <FormControl size="small" sx={{ flex: 1.2 }}>
                                            <InputLabel>{t('workflow.validation_type', 'Validation Type')}</InputLabel>
                                            <Select
                                                label={t('workflow.validation_type', 'Validation Type')}
                                                value={v.validationType || 'Required'}
                                                onChange={(e) => handleFieldChange({ validationType: e.target.value })}
                                            >
                                                {getValidationTypesForControl(control.type).map((vt) => (
                                                    <MenuItem key={vt} value={vt}>{vt}</MenuItem>
                                                ))}
                                            </Select>
                                        </FormControl>

                                        <FormControl size="small" sx={{ flex: 0.8 }}>
                                            <InputLabel>{t('workflow.severity', 'Severity')}</InputLabel>
                                            <Select
                                                label={t('workflow.severity', 'Severity')}
                                                value={v.severity || 'Error'}
                                                onChange={(e) => updateRequestControlsValidation(v.id, { severity: e.target.value })}
                                            >
                                                {['Error', 'Warning', 'Information'].map((sv) => (
                                                    <MenuItem key={sv} value={sv}>{sv}</MenuItem>
                                                ))}
                                            </Select>
                                        </FormControl>
                                    </Stack>

                                    {/* Expression / Rule Value — only shown for types that require a value */}
                                    {exprHint && (
                                        <TextField
                                            size="small"
                                            fullWidth
                                            label={t('workflow.validation_expression', 'Expression / Rule Value')}
                                            value={v.validationExpression || ''}
                                            placeholder={exprHint.placeholder}
                                            helperText={exprHint.hint}
                                            FormHelperTextProps={{ sx: { mx: 0, mt: 0.5, fontSize: '0.72rem' } }}
                                            onChange={(e) => handleFieldChange({ validationExpression: e.target.value })}
                                        />
                                    )}

                                    {/* Input Mask — shown for format-based types (Phone, Mobile, NationalID, IBAN, etc.) */}
                                    {MASK_TYPES.has(v.validationType) && (() => {
                                        const relevantPresets = MASK_PATTERNS.filter((p) => p.validationType === v.validationType);
                                        return (
                                            <Stack spacing={0.5}>
                                                <TextField
                                                    size="small"
                                                    fullWidth
                                                    label={t('workflow.input_mask', 'Input Mask')}
                                                    value={control.mask ?? ''}
                                                    placeholder={VALIDATION_TYPE_TO_MASK[v.validationType] ?? 'e.g. 000-000-0000'}
                                                    helperText={t('workflow.input_mask_hint', '0 = digit · a = letter · * = any')}
                                                    FormHelperTextProps={{ sx: { mx: 0, mt: 0.5, fontSize: '0.72rem' } }}
                                                    onChange={(e) => updateRequestControl(control.id, { mask: e.target.value || undefined })}
                                                />
                                                {relevantPresets.length > 0 && (
                                                    <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                                                        {relevantPresets.map((p) => (
                                                            <Chip
                                                                key={p.label}
                                                                label={p.label}
                                                                size="small"
                                                                variant={control.mask === p.mask ? 'filled' : 'outlined'}
                                                                color={control.mask === p.mask ? 'primary' : 'default'}
                                                                onClick={() => updateRequestControl(control.id, { mask: p.mask })}
                                                                sx={{ fontSize: '0.7rem', height: 22, cursor: 'pointer' }}
                                                            />
                                                        ))}
                                                        {control.mask && (
                                                            <Chip
                                                                label={t('common.clear', 'Clear')}
                                                                size="small"
                                                                variant="outlined"
                                                                color="error"
                                                                onClick={() => updateRequestControl(control.id, { mask: undefined })}
                                                                sx={{ fontSize: '0.7rem', height: 22, cursor: 'pointer' }}
                                                            />
                                                        )}
                                                    </Box>
                                                )}
                                            </Stack>
                                        );
                                    })()}

                                    {/* CustomExpression fields: Operator, Value, Value2 */}
                                    {isCustomExpr && (
                                        <Stack direction="row" spacing={1}>
                                            <FormControl size="small" sx={{ flex: 1 }}>
                                                <InputLabel>{t('workflow.operator', 'Operator')}</InputLabel>
                                                <Select
                                                    label={t('workflow.operator', 'Operator')}
                                                    value={v.operator || ''}
                                                    onChange={(e) => handleFieldChange({ operator: e.target.value })}
                                                >
                                                    <MenuItem value=""><em>({t('common.none', 'none')})</em></MenuItem>
                                                    {['=', '==', '!=', '>', '<', '>=', '<=', 'contains', 'isEmpty'].map((op) => (
                                                        <MenuItem key={op} value={op}>{op}</MenuItem>
                                                    ))}
                                                </Select>
                                            </FormControl>

                                            <TextField
                                                size="small"
                                                label={t('common.value', 'Value')}
                                                value={v.value || ''}
                                                fullWidth
                                                sx={{ flex: 1 }}
                                                onChange={(e) => handleFieldChange({ value: e.target.value })}
                                            />
                                        </Stack>
                                    )}

                                    {/* Bilingual Error Messages — only editable for CustomExpression */}
                                    {isCustomExpr && (
                                        <Stack spacing={1}>
                                            <TextField
                                                size="small"
                                                fullWidth
                                                label={t('workflow.err_msg_en', 'Error Message (EN)')}
                                                value={v.errorMessageEn || ''}
                                                onChange={(e) => updateRequestControlsValidation(v.id, { errorMessageEn: e.target.value })}
                                            />
                                            <TextField
                                                size="small"
                                                fullWidth
                                                label={t('workflow.err_msg_ar', 'Error Message (AR)')}
                                                value={v.errorMessageAr || ''}
                                                dir="rtl"
                                                onChange={(e) => updateRequestControlsValidation(v.id, { errorMessageAr: e.target.value })}
                                            />
                                        </Stack>
                                    )}

                                    {/* Active & Delete */}
                                    <Stack direction="row" alignItems="center" justifyContent="space-between">
                                        <FormControlLabel
                                            control={
                                                <Switch
                                                    size="small"
                                                    checked={v.isActive}
                                                    onChange={(e) => updateRequestControlsValidation(v.id, { isActive: e.target.checked })}
                                                />
                                            }
                                            label={t('common.active', 'Active')}
                                        />

                                        <IconButton
                                            size="small"
                                            color="error"
                                            onClick={() => deleteRequestControlsValidation(v.id)}
                                        >
                                            <Delete fontSize="small" />
                                        </IconButton>
                                    </Stack>
                                </Stack>
                            </Paper>
                        );
                    })}
            </Stack>

            <Divider />
            <Stack direction="row" alignItems="center">
                <Typography variant="subtitle2" sx={{ flexGrow: 1, fontWeight: 700 }}>
                    {t('workflow.transitions', 'Transitions')} ({controlTransitions.length})
                </Typography>
                <Button
                    size="small"
                    startIcon={<Add />}
                    onClick={addTransitionForControl}
                    sx={{ textTransform: 'none' }}
                >
                    {t('common.add', 'Add')}
                </Button>
            </Stack>
            <Stack spacing={1.5}>
                {controlTransitions.map((tr) => (
                    <Paper key={tr.id} variant="outlined" sx={{ p: 1.5, borderRadius: 1.5 }} onClick={(e) => e.stopPropagation()}>
                        <Stack spacing={1}>
                            {/* Row 1: Variable & Operator */}
                            <Stack direction="row" spacing={1}>
                                <FormControl size="small" sx={{ flex: 1 }} onClick={(e) => e.stopPropagation()}>
                                    <InputLabel>{t('workflow.variable', 'Variable')}</InputLabel>
                                    <Select
                                        label={t('workflow.variable', 'Variable')}
                                        value={tr.variableId || ''}
                                        onChange={(e) => updateTransition(tr.id, { variableId: e.target.value })}
                                    >
                                        <MenuItem value="">—</MenuItem>
                                        {variables.map((v) => (
                                            <MenuItem key={v.id} value={v.id}>
                                                {v.code ? `${v.code} - ` : ''}{isRtl ? v.nameAR || v.name : v.name}
                                            </MenuItem>
                                        ))}
                                    </Select>
                                </FormControl>

                                <FormControl size="small" sx={{ flex: 1 }} onClick={(e) => e.stopPropagation()}>
                                    <InputLabel>{t('workflow.operator', 'Operator')}</InputLabel>
                                    <Select
                                        label={t('workflow.operator', 'Operator')}
                                        value={tr.operatorId || ''}
                                        onChange={(e) => updateTransition(tr.id, { operatorId: e.target.value as number })}
                                    >
                                        <MenuItem value="">—</MenuItem>
                                        {operators.map((op) => (
                                            <MenuItem key={op.id} value={op.id}>
                                                {isRtl ? op.nameAR || op.name : op.name}
                                            </MenuItem>
                                        ))}
                                    </Select>
                                </FormControl>
                            </Stack>

                            {/* Row 2: Value & Target Step */}
                            <Stack direction="row" spacing={1} alignItems="center">
                                <Box sx={{ flex: 1 }} onClick={(e) => e.stopPropagation()}>
                                    {isClosedControl ? (
                                        <FormControl size="small" fullWidth onClick={(e) => e.stopPropagation()}>
                                            <InputLabel>{t('common.value', 'Value')}</InputLabel>
                                            <Select
                                                label={t('common.value', 'Value')}
                                                value={tr.value || ''}
                                                onChange={(e) => {
                                                    updateTransition(tr.id, { value: e.target.value as string });
                                                }}
                                            >
                                                <MenuItem value="">—</MenuItem>
                                                {control.type === 'checkbox' ? [
                                                    <MenuItem key="true" value="true">{t('common.yes', 'Yes')}</MenuItem>,
                                                    <MenuItem key="false" value="false">{t('common.no', 'No')}</MenuItem>
                                                ] : (
                                                    (control.optionsX || []).map((opt, idx) => (
                                                        <MenuItem key={idx} value={opt.value}>
                                                            {isRtl ? opt.ar || opt.en || opt.value : opt.en || opt.ar || opt.value}
                                                        </MenuItem>
                                                    ))
                                                )}
                                            </Select>
                                        </FormControl>
                                    ) : (
                                        <TextField
                                            size="small"
                                            fullWidth
                                            label={t('common.value', 'Value')}
                                            value={tr.value || ''}
                                            onClick={(e) => e.stopPropagation()}
                                            onChange={(e) => updateTransition(tr.id, { value: e.target.value })}
                                        />
                                    )}
                                </Box>

                                <FormControl size="small" sx={{ flex: 1 }} onClick={(e) => e.stopPropagation()}>
                                    <InputLabel>{t('workflow.target_step', 'Target Step')}</InputLabel>
                                    <Select
                                        label={t('workflow.target_step', 'Target Step')}
                                        value={tr.stepId || ''}
                                        onChange={(e) => updateTransition(tr.id, { stepId: e.target.value })}
                                    >
                                        <MenuItem value="">—</MenuItem>
                                        {steps.map((s) => (
                                            <MenuItem key={s.id} value={s.id}>
                                                {isRtl ? s.nameAR || s.name : s.name}
                                            </MenuItem>
                                        ))}
                                    </Select>
                                </FormControl>
                            </Stack>

                            {/* Row 3: Active & Delete */}
                            <Stack direction="row" alignItems="center" justifyContent="space-between" onClick={(e) => e.stopPropagation()}>
                                <FormControlLabel
                                    control={
                                        <Switch
                                            size="small"
                                            checked={tr.isActive}
                                            onChange={(e) => updateTransition(tr.id, { isActive: e.target.checked })}
                                        />
                                    }
                                    label={t('common.active', 'Active')}
                                />
                                <IconButton
                                    size="small"
                                    color="error"
                                    onClick={(e) => {
                                        e.stopPropagation();
                                        deleteTransition(tr.id);
                                    }}
                                >
                                    <Delete fontSize="small" />
                                </IconButton>
                            </Stack>
                        </Stack>
                    </Paper>
                ))}
                {controlTransitions.length === 0 && (
                    <Typography variant="caption" color="text.secondary" align="center">
                        {t('workflow.no_transitions_yet', 'No transitions yet.')}
                    </Typography>
                )}
            </Stack>
        </Stack>
    );
});

RequestControlSettingsPanel.displayName = 'RequestControlSettingsPanel';
