using IAX.IXApi.Infrastructure.Persistence;
using IAX.IXApi.Modules.Workflow.Performers;
using Microsoft.EntityFrameworkCore;

namespace IAX.IXApi.Infrastructure.Persistence.Seeding.Chunks;

public sealed partial class WfProcessSeedData
{
    private static async Task SeedPerformersAsync(
        ApplicationDbContext db,
        string owner,
        CancellationToken ct)
    {
        var existingIds = await db.WfPerformers.IgnoreQueryFilters()
            .Select(x => x.RecId)
            .ToListAsync(ct);

        var toAdd = new List<WfPerformer>();

        var items = new[]
        {
            new { RecId = 12L, Name = "applicant", IsActive = true, PerformerTypeId = (short)3, RelatedField = (long?)null, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 13L, Name = "المدير الاول للمقدم الطلب", IsActive = true, PerformerTypeId = (short)3, RelatedField = (long?)null, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 14L, Name = "المدير الثاني للمقدم الطلب", IsActive = true, PerformerTypeId = (short)3, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = true, IsManager3 = false, IsManager4 = false },
            new { RecId = 15L, Name = "المدير الثالث للمقدم الطلب", IsActive = true, PerformerTypeId = (short)3, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = true, IsManager4 = false },
            new { RecId = 16L, Name = "المدير الثالث للمقدم الطلب", IsActive = true, PerformerTypeId = (short)3, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = true },
            new { RecId = 17L, Name = "Raouf Abdullah ali hizam", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 18L, Name = "Rayan Abdullah ali hzam", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 19L, Name = "Assistant CEO", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 20L, Name = "مشرف المنطقة - تقرير جرد", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20536L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 21L, Name = "مدير المعرض - ايقاع مخالفة", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20530L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 22L, Name = "الموظف المخالف", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)37642L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 23L, Name = "نحا مبارك محماس القحطاني", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 24L, Name = "Resources Employment / Duaa Al-Nimreen", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 25L, Name = "muhammad ibrahim muhmmad thabet", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 26L, Name = "دعم الفني", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 27L, Name = "Mahmoud Mohammed Hussein Mahmoud", IsActive = false, PerformerTypeId = (short)1, RelatedField = (long?)2L, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 28L, Name = "اسم  المعرض - تقرير جرد", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)37665L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 29L, Name = "Abdul Salam Abdul Jabbar Ali Al-Sanea", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 30L, Name = "اسم مسوؤل الجوده - طلب تسجيل فديو", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)37681L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 31L, Name = "HAMADA Khalaf Abdul Rahim Hassan", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 32L, Name = "Kenan Abdullah Ali Hizam", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 33L, Name = "مشرف منطقة - رصد مخالفة", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)37710L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 34L, Name = "البائع  1 - تقرير جرد", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)37714L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 35L, Name = "مشرف منطقة - تاكيد جرد", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38140L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 36L, Name = "مدير اول - تاكيد جرد", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20820L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 37L, Name = "سامح عنتر فرج البرني", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 38L, Name = "عبدالعزيز سعود محمد الحربي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 39L, Name = "مجاهد عبدالله محمد غانم", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 40L, Name = "فواز صالح ناصر الغصن", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 41L, Name = "فراس ابراهيم النويصر", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 42L, Name = "Hamaz/Mowaqqat Badal Al-Zaki", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 43L, Name = "محمد المتولى محمد جميل", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 44L, Name = "داؤود محمد الخير الانصاري", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 45L, Name = "ماجد قائد طاهر السروري", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 46L, Name = "مد ساكيل احماد", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 47L, Name = "Engineer/Al-Tayeb", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 48L, Name = "Financial Manager / Hossam", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 49L, Name = "محاسب المبيعات / محمد محسن", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 50L, Name = "محمود احمد حمزة احمد", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 51L, Name = "مشرف المنطقة 1 - استئجار معرض", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)37780L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 52L, Name = "مستلم البضاعة - استئجار معرض", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)37786L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 53L, Name = "mohammad Hamaaz", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 54L, Name = "رئيس الحسابات/ حمدي احمد", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 55L, Name = "الموظف المخالف -  رصد مخالفة موظف", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)37801L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 56L, Name = "مدير إدارة الموظف المخالف - رصد مخالفة موظف", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)37801L, IsEmployee = false, IsManager1 = false, IsManager2 = true, IsManager3 = false, IsManager4 = false },
            new { RecId = 57L, Name = "المدير المباشر للموظف المخالف - رصد مخالفة موظف", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20584L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 58L, Name = "اسم الفرع - تحويل اصناف بين الفروع", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20591L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 59L, Name = "الجودة 6 - رفع شكوى", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 60L, Name = "Resources Raghad", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 61L, Name = "Fatima Human Resources", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 62L, Name = "ميسر وادي الكعيط", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 63L, Name = "مدير المنطقة - عجز صندوق", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20601L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 64L, Name = "Movement official/Baraa", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)20616L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 65L, Name = "تميم عبدالله علي حزام", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 66L, Name = "مدير الاول - صرف بضاعة", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20542L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 67L, Name = "مدير الثاني - صرف بضاعة", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20542L, IsEmployee = false, IsManager1 = false, IsManager2 = true, IsManager3 = false, IsManager4 = false },
            new { RecId = 68L, Name = "محمد محسن الشرباصي الغيطاني", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 69L, Name = "اسم الفرع - تركيب كاميرات", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20673L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 70L, Name = "اية محمد الحوراني", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 71L, Name = "مستودع اعادة التاهيل", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 72L, Name = "Dawood Muhammad Al-Ansari", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 73L, Name = "Vinay kumar", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 74L, Name = "رضا حمدي مصطفى رزق", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 75L, Name = "احمد رجب جبرئيل حافظ", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 76L, Name = "عامر سهيل خاجة", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 77L, Name = "تميم عبدالله علي حزام", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 78L, Name = "احمد بدران السيد حسن", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 79L, Name = "الموارد - فاطمة", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 80L, Name = "HR monitored a violation by a vendor and an employee/", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 81L, Name = "امجاد علي اشرف علي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)20792L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 82L, Name = "مدير اول اخلاء طرف", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20815L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 83L, Name = "مسؤول السداد / هشام عبدالقادر عبدالنبي السيد", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 84L, Name = "مصطفى عدنان محمد صالح الفقي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 85L, Name = "هديل عبدالقادر  محمد الحوامدة", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 86L, Name = "غمدان علي علي سعيد", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 87L, Name = "باسم خالد علي الجماعي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 88L, Name = "بشار بشير احمد الحي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 89L, Name = "جبران محمد مرشد اليافعي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 90L, Name = "مزنة محمد الحمادي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 91L, Name = "عمار عبده صالح الغفير", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 92L, Name = "الجودة 8", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 93L, Name = "ريناد علي العامري", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 94L, Name = "عبدالرحمن القاسمي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 95L, Name = "Legal Ebrar Al-Mutairi", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 96L, Name = "موظف سداد مالية", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39828L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 97L, Name = "Maintenance Officer", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 98L, Name = "المتجر الالكتروني (27)", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 99L, Name = "Store accountant", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 100L, Name = "Recruitment specific", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 101L, Name = "Payment officer", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 102L, Name = "معرض - رصد مخالفة بائع", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20530L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 103L, Name = "Customer Service Halima", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 104L, Name = "CEO", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 105L, Name = "الفرع - طلب تقرير جرد", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20536L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 106L, Name = "Customer Service Supervisor", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 107L, Name = "الفرع - حركة سير الشحنة", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38268L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 108L, Name = "السائق - حركة سير شحنة", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)20974L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 109L, Name = "Quality 2", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 110L, Name = "الموظف المعني - مخالفات الحكومية", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38305L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 111L, Name = "الموظف المختص - مخالفات الحكومية", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21015L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 112L, Name = "Aseel Khaled Talal Alaameri", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 113L, Name = "محاسب المالية - تصفية عهدة", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38326L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 114L, Name = "تحقيق موظف المحقق معه", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38340L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 115L, Name = "تحقيق الشاهد", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38352L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 116L, Name = "Recruitment Officer", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 117L, Name = "Purchasing Officer", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 118L, Name = "Purchasing Accountant/Ahmed Badran", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 119L, Name = "Convert cover up", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 120L, Name = "Municipality Licensing Follow-up Officer Lujain", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 121L, Name = "إيثار خالد ناصر المطوع", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 122L, Name = "المستودع الرئيسي طويق 4", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 123L, Name = "فرع - استلام طلبية", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21092L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 124L, Name = "الموظف المعني - شكوى رفض توقيع", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21095L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 125L, Name = "مستلم التحويل - تحويل واستلام فروع", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21106L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 126L, Name = "الفرع المحول اليه - تحويل واستلام", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38546L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 127L, Name = "موظف - شحن هدايا عملاء", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38551L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 128L, Name = "Purchasing accountant", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 129L, Name = "Orders Officer", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 130L, Name = "Orders Officer", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 131L, Name = "Analysis", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 132L, Name = "Operations Manager", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 133L, Name = "Human resources", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 134L, Name = "Internal audit", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 135L, Name = "محاسب عهدة مصروفات", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39367L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 136L, Name = "تحويل لموظف الموارد استقالة", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38640L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 137L, Name = "موظف متغيب عن العمل", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21182L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 138L, Name = "مدير موظف تغيب عن العمل", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21182L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 139L, Name = "موظف _ انقطاع موظف", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21184L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 140L, Name = "مدير _ انقطاع موظف", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21184L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 141L, Name = "Human Resources 2 Aya/Sja", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 142L, Name = "محاسب المبيعات اليومية إغلاق", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 143L, Name = "المعتدي - شكوى تعدي", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21193L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 144L, Name = "الشاهد - شكوى تعدي", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)38690L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 145L, Name = "محمد تركي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 146L, Name = "HR Employee for", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 147L, Name = "اسم موظف مخالفة لوجستيك", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21315L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 148L, Name = "Human Resources Officer Raghad Al-Shoubaki", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 149L, Name = "Orders Officer Muhammad Naseem", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 150L, Name = "الموظف سداد", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38802L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 151L, Name = "Former employee", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21450L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 152L, Name = "Shipping policies / Amal", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 153L, Name = "Employee", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21479L, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 154L, Name = "Receiving astlam", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 155L, Name = "Quality Abdul Wahab", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 156L, Name = "Video Design Officer/osamh", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 157L, Name = "Marketing Officer / Zahid", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 158L, Name = "LED screens/Waqar", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 159L, Name = "The employee's first manager", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21510L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 160L, Name = "Name of the employee concerned", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38980L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 161L, Name = "IT Support Specialist", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39010L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 162L, Name = "The employee concerned / obstructing the workflow", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39013L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 163L, Name = "Area Manager/Franchise to Tobacco Conversion", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39021L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 164L, Name = "New recipient", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)38811L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 165L, Name = "الموظف المختص / خدمات عامة", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39896L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 166L, Name = "Advertiser Coordination / Jamila Abdel Wahab", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 167L, Name = "الموظف المخالف/ خدمة عملاء", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21596L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 168L, Name = "To the competent inventory employee", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39127L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 169L, Name = "Tamir Alsayid Abdalmutee", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 170L, Name = "The employee's first manager", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21596L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 171L, Name = "الانشاءات /عبدالرحمن القاسمي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 172L, Name = "Amman Warehouse", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 173L, Name = "Human Resources / Yara", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 174L, Name = "Area Supervisor", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21604L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 175L, Name = "الفرع جرد", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21621L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 176L, Name = "الفرع جرد 1", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21621L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 177L, Name = "الفرع جرد 2", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39267L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 178L, Name = "عبدالرحمن مستودع الامارات", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 179L, Name = "Covenant Official / Abdul-Matin", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 180L, Name = "Finance / Mohammed Aslam", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 181L, Name = "Niche Management Manager / Mr. Yem", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 182L, Name = "The concerned employee/Saddad Niche", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39382L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 183L, Name = "فهد الكاملي", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 184L, Name = "Cost Controller / Ebrar", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 185L, Name = "Human Resources / AYA", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 186L, Name = "Staff Member / Store Returns", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)39421L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 187L, Name = "The competent employee", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)39428L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 188L, Name = "موظف مقدم", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39442L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 189L, Name = "المختص العهد", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)39367L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 190L, Name = "موظف الدولة", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)39554L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 191L, Name = "The concerned employee/checks", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39554L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 192L, Name = "Southern Region Inventory Supervisor / Faisal", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 193L, Name = "Northern Region Inventory Supervisor / Mohammed", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 194L, Name = "Quality Officer", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39570L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 195L, Name = "/chik/competent employee", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39579L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 196L, Name = "The competent employee/", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39595L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 197L, Name = "International Transfers Officer/Lal bahadur", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 198L, Name = "Specialized covenant accountant", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39607L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 199L, Name = "الموظف شكوى فروع", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)21226L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 200L, Name = "عملاء فروع ش", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21225L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 201L, Name = "عملاء فروع م", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21225L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 202L, Name = "International Branch Accountant Mr. Shima", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 203L, Name = "cco employee coding support", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 204L, Name = "Test", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21226L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 205L, Name = "Human Resources / Fatima", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 206L, Name = "Disciplinary action taken against employee in violation of regulations.", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39662L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 207L, Name = "TEST", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 208L, Name = "Kuwait Warehouse Manager/Mohammed Siddiq", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 209L, Name = "Financial Manager / Hossam", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 210L, Name = "The relevant employee / Construction accountant", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)39739L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 211L, Name = "The specialized accountant", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39779L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 212L, Name = "محاسب مختص - ت", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39739L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 213L, Name = "Resources Shatha", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 214L, Name = "Human Resources/Franchise Specialist", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39755L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 215L, Name = "Osama Suleiman / Niche", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 216L, Name = "Osama Suleiman / Niche", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 217L, Name = "Assistant General Manager", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 218L, Name = "Purchasing Manager / Salah Adham", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 219L, Name = "International Branch Accountant", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 220L, Name = "Quality Specialist", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39817L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 221L, Name = "محاسب فروع", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39833L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 222L, Name = "The one in charge", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21930L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 223L, Name = "Astlam/", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 224L, Name = "روتين مخزون", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21933L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 225L, Name = "روتين مخزون 1", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21933L, IsEmployee = false, IsManager1 = true, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 226L, Name = "روتين مخزون 2", IsActive = true, PerformerTypeId = (short)4, RelatedField = (long?)21934L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 227L, Name = "Shipping coordinator", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 228L, Name = "Goodness Observer", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 229L, Name = "International Accountant", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39878L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 230L, Name = "Warehouse Manager / Abu Bakr", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 231L, Name = "Accountant Specialist / Exhibition Evaluation", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39893L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 232L, Name = "Accountant/General Services", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39896L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 233L, Name = "موظف خدمات عامة", IsActive = false, PerformerTypeId = (short)5, RelatedField = (long?)39896L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 234L, Name = "Assistant General Manager1", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 235L, Name = "Procurement Officer", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 236L, Name = "نديم الخولاني", IsActive = true, PerformerTypeId = (short)2, RelatedField = (long?)null, IsEmployee = false, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 237L, Name = "Accountant/Gift Disbursement", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39940L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
            new { RecId = 238L, Name = "محاسب سداد خدمات عامة", IsActive = true, PerformerTypeId = (short)5, RelatedField = (long?)39948L, IsEmployee = true, IsManager1 = false, IsManager2 = false, IsManager3 = false, IsManager4 = false },
        };

        foreach (var item in items)
        {
            if (!existingIds.Contains(item.RecId))
            {
                toAdd.Add(new WfPerformer
                {
                    RecId = item.RecId,
                    Code = "PERF" + item.RecId,
                    Name = item.Name,
                    // Source rows use legacy performer-type IDs (2, 4, and 5)
                    // that do not exist in the supported master-data catalog.
                    // Preserve the row's employee/manager/related-field flags and
                    // map imported performers to the supported relational type.
                    PerformerTypeId = 1,
                    RelatedField = item.RelatedField,
                    IsApplicant = item.PerformerTypeId == 3,
                    IsEmployee = item.IsEmployee,
                    IsManager1 = item.IsManager1,
                    IsManager2 = item.IsManager2,
                    IsManager3 = item.IsManager3,
                    IsManager4 = item.IsManager4,
                    CreatedBy = owner,
                    OwnerAccountId = owner,
                    IsActive = item.IsActive
                });
            }
        }

        if (toAdd.Any())
        {
            await db.WfPerformers.AddRangeAsync(toAdd, ct);
            
            await db.Database.OpenConnectionAsync(ct);
            try
            {
                await db.Database.ExecuteSqlRawAsync("SET IDENTITY_INSERT WfPerformers ON", ct);
                await db.SaveChangesAsync(ct);
                await db.Database.ExecuteSqlRawAsync("SET IDENTITY_INSERT WfPerformers OFF", ct);
            }
            finally
            {
                await db.Database.CloseConnectionAsync();
            }
        }
    }
}
