<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IAX.IXApi.Modules.Communication</RootNamespace>
    <AssemblyName>IAX.IXApi.Modules.Communication</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
    <ProjectReference Include="..\..\Shared\IAX.IXApi.Shared.csproj" />
    <ProjectReference Include="..\Identity\IAX.IXApi.Modules.Identity.csproj" />
    <ProjectReference Include="..\Administration\IAX.IXApi.Modules.Administration.csproj" />
    <ProjectReference Include="..\Organization\IAX.IXApi.Modules.Organization.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
