<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>IAX.IXApi.Modules.Communication</RootNamespace>
    <AssemblyName>IAX.IXApi.Modules.Communication</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\IAX.IXApi.Infrastructure.csproj" />
  </ItemGroup>
</Project>
