using Mapster;
using IAX.IXApi.Modules.Finance.Entities;
using IAX.IXApi.Modules.Finance.Common;

namespace IAX.IXApi.Modules.Finance.Inventory;

public sealed class InventLocationMapping : IRegister
{
    public void Register(TypeAdapterConfig config)
    {
        config.NewConfig<LocationInputDto, InventLocation>().IgnoreNonMapped(true)
            .Map(d => d.Name, i => i.Name.Trim())
            .Map(d => d.InventSiteId, i => i.InventSiteId.Trim())
            .Map(d => d.InventLocationType, i => (InventLocationType)i.InventLocationType)
            .Map(d => d.InventLocationLevel, i => i.InventLocationLevel)
            .Map(d => d.InventLocationIdTransit, i => i.InventLocationIdTransit.Trim())
            .Map(d => d.InventLocationIdQuarantine, i => i.InventLocationIdQuarantine.Trim())
            .Map(d => d.InventLocationIdReqMain, i => i.InventLocationIdReqMain.Trim())
            .Map(d => d.ItmInventLocationIdGit, i => i.ItmInventLocationIdGit.Trim())
            .Map(d => d.ItmInventLocationIdUnder, i => i.ItmInventLocationIdUnder.Trim())
            .Map(d => d.VendAccount, i => i.VendAccount.Trim())
            .Map(d => d.WorkflowApproval, i => i.WorkflowApproval?NoYes.Yes:NoYes.No)
            .Map(d => d.Manual, i => i.Manual?NoYes.Yes:NoYes.No)
            .Map(d => d.ReqRefill, i => i.ReqRefill?NoYes.Yes:NoYes.No)
            .Map(d => d.WmsLocationIdDefaultReceipt, i => i.WmsLocationIdDefaultReceipt.Trim())
            .Map(d => d.WmsLocationIdDefaultIssue, i => i.WmsLocationIdDefaultIssue.Trim())
            .Map(d => d.DefaultProductionInputLocation, i => i.DefaultProductionInputLocation.Trim())
            .Map(d => d.DefaultProductionFinishGoodsLocation, i => i.DefaultProductionFinishGoodsLocation.Trim())
            .Map(d => d.DefaultKanbanFinishedGoodsLocation, i => i.DefaultKanbanFinishedGoodsLocation.Trim())
            .Map(d => d.DefaultReturnCreditOnlyLocation, i => i.DefaultReturnCreditOnlyLocation.Trim())
            .Map(d => d.DefaultStatusID, i => i.DefaultStatusId.Trim())
            .Map(d => d.WmsRackFormat, i => i.WmsRackFormat.Trim())
            .Map(d => d.WmsLevelFormat, i => i.WmsLevelFormat.Trim())
            .Map(d => d.WmsPositionFormat, i => i.WmsPositionFormat.Trim())
            .Map(d => d.WhsEnabled, i => (i.WhsEnabled ? NoYes.Yes : NoYes.No))
            .Map(d => d.WarehouseAutoReleaseReservation, i => (i.WarehouseAutoReleaseReservation ? NoYes.Yes : NoYes.No))
            .Map(d => d.AutoUpdateShipment, i => (i.AutoUpdateShipment ? NoYes.Yes : NoYes.No))
            .Map(d => d.ReserveAtLoadPost, i => (i.ReserveAtLoadPost ? NoYes.Yes : NoYes.No))
            .Map(d => d.DecrementLoadLine, i => (i.DecrementLoadLine ? NoYes.Yes : NoYes.No))
            .Map(d => d.PrintBolBeforeShipConfirm, i => (i.PrintBolBeforeShipConfirm ? NoYes.Yes : NoYes.No))
            .Map(d => d.CycleCountAllowPalletMove, i => (i.CycleCountAllowPalletMove ? NoYes.Yes : NoYes.No))
            .Map(d => d.AllowLaborStandards, i => (i.AllowLaborStandards ? NoYes.Yes : NoYes.No))
            .Map(d => d.AllowMarkingReservationRemoval, i => (i.AllowMarkingReservationRemoval ? NoYes.Yes : NoYes.No))
            .Map(d => d.UseWmsOrders, i => (i.UseWmsOrders ? NoYes.Yes : NoYes.No))
            .Map(d => d.WmsAisleNameActive, i => (i.WmsAisleNameActive ? NoYes.Yes : NoYes.No))
            .Map(d => d.WmsRackNameActive, i => (i.WmsRackNameActive ? NoYes.Yes : NoYes.No))
            .Map(d => d.WmsLevelNameActive, i => (i.WmsLevelNameActive ? NoYes.Yes : NoYes.No))
            .Map(d => d.WmsPositionNameActive, i => (i.WmsPositionNameActive ? NoYes.Yes : NoYes.No))
            .Map(d => d.UniqueCheckDigits, i => (i.UniqueCheckDigits ? NoYes.Yes : NoYes.No))
            .Map(d => d.EnableQualityManagement, i => (i.EnableQualityManagement ? NoYes.Yes : NoYes.No))
            .Map(d => d.RemoveInventBlockingOnStatusChange, i => (i.RemoveInventBlockingOnStatusChange ? NoYes.Yes : NoYes.No))
            .Map(d => d.ProdReserveOnlyWhse, i => (i.ProdReserveOnlyWhse ? NoYes.Yes : NoYes.No))
            .Map(d => d.WhsProdOrderBackflushMustUseReservedQty, i => (i.WhsProdOrderBackflushMustUseReservedQty ? NoYes.Yes : NoYes.No))
            .Map(d => d.FshStore, i => (i.FshStore ? NoYes.Yes : NoYes.No))
            .Map(d => d.ConsolidateShipAtRtw, i => (i.ConsolidateShipAtRtw ? NoYes.Yes : NoYes.No))
            .Map(d => d.RetailInventNegPhysical, i => (i.RetailInventNegPhysical ? NoYes.Yes : NoYes.No))
            .Map(d => d.RetailInventNegFinancial, i => (i.RetailInventNegFinancial ? NoYes.Yes : NoYes.No))
            .Map(d => d.EnableExternalWarehouse, i => (i.EnableExternalWarehouse ? NoYes.Yes : NoYes.No))
            .Map(d => d.MaxPickingRouteTime, i => i.MaxPickingRouteTime)
            .Map(d => d.PickingLineTime, i => i.PickingLineTime);

        config.NewConfig<InventLocation, InventLocationResponseDto>().IgnoreNonMapped(true)
            .Map(d => d.Id, x => x.RecId.ToString())
            .Map(d => d.RecId, x => x.RecId)
            .Map(d => d.InventLocationId, x => x.InventLocationId)
            .Map(d => d.Name, x => x.Name)
            .Map(d => d.InventSiteId, x => x.InventSiteId)
            .Map(d => d.InventLocationType, x => (int)x.InventLocationType)
            .Map(d => d.InventLocationLevel, x => x.InventLocationLevel)
            .Map(d => d.InventLocationIdTransit, x => x.InventLocationIdTransit)
            .Map(d => d.InventLocationIdQuarantine, x => x.InventLocationIdQuarantine)
            .Map(d => d.InventLocationIdReqMain, x => x.InventLocationIdReqMain)
            .Map(d => d.ItmInventLocationIdGit, x => x.ItmInventLocationIdGit)
            .Map(d => d.ItmInventLocationIdUnder, x => x.ItmInventLocationIdUnder)
            .Map(d => d.VendAccount, x => x.VendAccount)
            .Map(d => d.WorkflowApproval, x => x.WorkflowApproval==NoYes.Yes)
            .Map(d => d.Manual, x => x.Manual==NoYes.Yes)
            .Map(d => d.ReqRefill, x => x.ReqRefill==NoYes.Yes)
            .Map(d => d.WmsLocationIdDefaultReceipt, x => x.WmsLocationIdDefaultReceipt)
            .Map(d => d.WmsLocationIdDefaultIssue, x => x.WmsLocationIdDefaultIssue)
            .Map(d => d.DefaultProductionInputLocation, x => x.DefaultProductionInputLocation)
            .Map(d => d.DefaultProductionFinishGoodsLocation, x => x.DefaultProductionFinishGoodsLocation)
            .Map(d => d.DefaultKanbanFinishedGoodsLocation, x => x.DefaultKanbanFinishedGoodsLocation)
            .Map(d => d.DefaultReturnCreditOnlyLocation, x => x.DefaultReturnCreditOnlyLocation)
            .Map(d => d.DefaultStatusId, x => x.DefaultStatusID)
            .Map(d => d.WmsRackFormat, x => x.WmsRackFormat)
            .Map(d => d.WmsLevelFormat, x => x.WmsLevelFormat)
            .Map(d => d.WmsPositionFormat, x => x.WmsPositionFormat)
            .Map(d => d.WhsEnabled, x => x.WhsEnabled==NoYes.Yes)
            .Map(d => d.WarehouseAutoReleaseReservation, x => x.WarehouseAutoReleaseReservation==NoYes.Yes)
            .Map(d => d.AutoUpdateShipment, x => x.AutoUpdateShipment==NoYes.Yes)
            .Map(d => d.ReserveAtLoadPost, x => x.ReserveAtLoadPost==NoYes.Yes)
            .Map(d => d.DecrementLoadLine, x => x.DecrementLoadLine==NoYes.Yes)
            .Map(d => d.PrintBolBeforeShipConfirm, x => x.PrintBolBeforeShipConfirm==NoYes.Yes)
            .Map(d => d.CycleCountAllowPalletMove, x => x.CycleCountAllowPalletMove==NoYes.Yes)
            .Map(d => d.AllowLaborStandards, x => x.AllowLaborStandards==NoYes.Yes)
            .Map(d => d.AllowMarkingReservationRemoval, x => x.AllowMarkingReservationRemoval==NoYes.Yes)
            .Map(d => d.UseWmsOrders, x => x.UseWmsOrders==NoYes.Yes)
            .Map(d => d.WmsAisleNameActive, x => x.WmsAisleNameActive==NoYes.Yes)
            .Map(d => d.WmsRackNameActive, x => x.WmsRackNameActive==NoYes.Yes)
            .Map(d => d.WmsLevelNameActive, x => x.WmsLevelNameActive==NoYes.Yes)
            .Map(d => d.WmsPositionNameActive, x => x.WmsPositionNameActive==NoYes.Yes)
            .Map(d => d.UniqueCheckDigits, x => x.UniqueCheckDigits==NoYes.Yes)
            .Map(d => d.EnableQualityManagement, x => x.EnableQualityManagement==NoYes.Yes)
            .Map(d => d.RemoveInventBlockingOnStatusChange, x => x.RemoveInventBlockingOnStatusChange==NoYes.Yes)
            .Map(d => d.ProdReserveOnlyWhse, x => x.ProdReserveOnlyWhse==NoYes.Yes)
            .Map(d => d.WhsProdOrderBackflushMustUseReservedQty, x => x.WhsProdOrderBackflushMustUseReservedQty==NoYes.Yes)
            .Map(d => d.FshStore, x => x.FshStore==NoYes.Yes)
            .Map(d => d.ConsolidateShipAtRtw, x => x.ConsolidateShipAtRtw==NoYes.Yes)
            .Map(d => d.RetailInventNegPhysical, x => x.RetailInventNegPhysical==NoYes.Yes)
            .Map(d => d.RetailInventNegFinancial, x => x.RetailInventNegFinancial==NoYes.Yes)
            .Map(d => d.EnableExternalWarehouse, x => x.EnableExternalWarehouse==NoYes.Yes)
            .Map(d => d.MaxPickingRouteTime, x => x.MaxPickingRouteTime)
            .Map(d => d.PickingLineTime, x => x.PickingLineTime);
    }
}
