using System;
using System.ComponentModel.DataAnnotations;
using IAX.IXApi.Shared.Application.Contracts;
using IAX.IXApi.Modules.Finance.Common;

namespace IAX.IXApi.Modules.Finance.Shared.Features
{
    public class MarkupTransDto : EntityDto<long>
    {
        public string MarkupCode { get; set; } = string.Empty;
        public decimal LineNum { get; set; }
        public DateTime TransDate { get; set; }
        public string Txt { get; set; } = string.Empty;
        public string Voucher { get; set; } = string.Empty;
        public MarkupCategory MarkupCategory { get; set; }
        public MarkupModuleCategory ModuleCategory { get; set; }
        public MarkupModuleType ModuleType { get; set; }
        public long TransRecId { get; set; }
        public int TransTableId { get; set; }
        public long OrigRecId { get; set; }
        public int OrigTableId { get; set; }
        public string CurrencyCode { get; set; } = string.Empty;
        public decimal Value { get; set; }
        public decimal Posted { get; set; }
        public decimal PreviousValue { get; set; }
        public decimal CalculatedAmount { get; set; }
        public decimal CalculatedProratedAmount { get; set; }
        public decimal FromAmount { get; set; }
        public decimal ToAmount { get; set; }
        public NoYes Keep { get; set; }
        public NoYes IsCompound { get; set; }
        public NoYes IsAutoCharge { get; set; }
        public NoYes IsTieredCharge { get; set; }
        public string TaxGroup { get; set; } = string.Empty;
        public string TaxItemGroup { get; set; } = string.Empty;
        public decimal TaxAmount { get; set; }
        public NoYes OverrideSalesTax { get; set; }
        public NoYes TaxAutoGenerated { get; set; }
        public DocumentStatus DocumentStatus { get; set; }
    }
}