using DocumentFormat.OpenXml.Office2010.CustomUI;
using IAX.IXApi.Modules.Finance.Common;
using IAX.IXApi.Modules.Finance.Shared.Features;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IAX.IXApi.Modules.Finance.Entities
{
    [Table("TaxJournalTrans")]
    public class TaxJournalTrans : Entity<long>
    {
        //----------------------------------------- Core Identity & Framework Traces
        // Basic Properties
        public DateTime TransDate { get; set; }
        public long TransRecId { get; set; }  // System Record ID reference to the driving transaction document
        public int TransTableId { get; set; } // System Table ID reference identifying the source entity map context

        [Required]
        [StringLength(FieldLengths.TaxCode)]
        public string TaxCode { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.TaxGroup)]
        public string TaxGroup { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.TaxItemGroup)]
        public string TaxItemGroup { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.InventTransId)]
        public string InventTransId { get; set; } = string.Empty; // Cross-link to inventory tracking lines if applicable

        // ==========================================================
        // Localized/Reporting Document Currencies
        // ==========================================================
        // Basic Properties
        [Required]
        [StringLength(FieldLengths.SourceCurrencyCode)]
        public string SourceCurrencyCode { get; set; } = string.Empty;

        public decimal SourceBaseAmountCur { get; set; }
        public decimal SourceTaxAmountCur { get; set; }
        public decimal SourceRegulateAmountCur { get; set; } // User-adjusted or manually overridden tax amount trace

        // ==========================================================
        // Consolidated Accounting Currency (Accounting / Base Valuation)
        // ==========================================================
        // Basic Properties
        public decimal TaxBaseAmount { get; set; } // Final calculated basis valuation in local accounting currency
        public decimal TaxAmount { get; set; }     // Final posted tax payload value in local accounting currency
        public decimal TaxBaseQty { get; set; }    // Unit metrics baseline if calculation engine is quantity-driven
        public decimal TaxValue { get; set; }      // Evaluated actual percentage rate or unit multi-tier value used

        // ==========================================================
        // Calculation Logic Filters & Taxing States
        // ==========================================================
        // Enum Properties
        public TaxDirection TaxDirection { get; set; } // Sales tax, Purchase tax, Use tax, Reverse charge matrix, etc.
        public TaxOrigin TaxOrigin { get; set; }       // Calculation engine core mechanism (Percentage, Quantity, Gross, etc.)
        public NoYes TaxAutoGenerated { get; set; }    // System automated calculation engine vs. manual journal override entry

        // ==========================================================
        // Tax Exemption Matrix
        // ==========================================================
        // Basic Properties
        [Required]
        [StringLength(FieldLengths.ExemptCode)]
        public string ExemptCode { get; set; } = string.Empty; // Regulatory reason reference string

        // Enum Properties
        public NoYes ExemptTax { get; set; }

        // ==========================================================
        // Cross-Border & Regional Customs Declarations
        // ==========================================================
        // Enum Properties
        public NoYes EuroTriangulation { get; set; } // European Union multi-party legal trade exception indicator

        // ==========================================================
        // Document Generation & Ledger Postings
        // ==========================================================
        // Basic Properties
        [Required]
        [StringLength(FieldLengths.PrintCode)]
        public string PrintCode { get; set; } = string.Empty;

        public long OperationLedgerDimension { get; set; } // Master financial dimension set pointing to GL offsets

        // Enum Properties
        public TaxPrintDetail TaxPrintDetail { get; set; }


        #region Navigation Properties Row

//         [ForeignKey(nameof(TaxCode))]
//         public virtual TaxTable? TaxCodeConfiguration { get; set; }

//         [ForeignKey(nameof(TaxGroup))]
//         public virtual TaxGroupHeading? AppliedTaxGroup { get; set; }

//         [ForeignKey(nameof(OperationLedgerDimension))]
//         public virtual DimensionAttributeValueCombination? OffsetAccountCombination { get; set; }

//         [ForeignKey(nameof(TaxItemGroup))]
//         public virtual TaxItemGroupHeading? AppliedTaxItemGroup { get; set; }

//         [ForeignKey(nameof(SourceCurrencyCode))]
//         public virtual Currency? SourceCurrency { get; set; }

        #endregion
    }
}

