using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using IAX.IXApi.Modules.Finance.Shared.Features;
using IAX.IXApi.Modules.Finance.Common;

namespace IAX.IXApi.Modules.Finance.Entities
{
    [Table("TaxTrans")]
    public class TaxTrans : Entity<long>
    {
        //----------------------------------------- Core Identity & Document Traces
        // Basic Properties
        public DateTime TransDate { get; set; }

        [Required]
        [StringLength(FieldLengths.Voucher)]
        public string Voucher { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.JournalNum)]
        public string JournalNum { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.TaxCode)]
        public string TaxCode { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.TaxGroup)]
        public string TaxGroup { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.TaxItemGroup)]
        public string TaxItemGroup { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.InventTransId)]
        public string InventTransId { get; set; } = string.Empty;

        // ==========================================================
        // Sub-Ledger Document Relationship Maps
        // ==========================================================
        // Basic Properties
        public long SourceRecId { get; set; }
        public int SourceTableId { get; set; }
        public long SourceDocumentLine { get; set; }
        public int HeadingTableId { get; set; }

        // ==========================================================
        // Source Document Multi-Currency Framework
        // ==========================================================
        // Basic Properties
        [Required]
        [StringLength(FieldLengths.SourceCurrencyCode)]
        public string SourceCurrencyCode { get; set; } = string.Empty;

        public decimal SourceBaseAmountCur { get; set; }
        public decimal SourceBaseAmountCurRegulated { get; set; }
        public decimal SourceTaxAmountCur { get; set; }
        public decimal SourceRegulateAmountCur { get; set; }

        // ==========================================================
        // System Currencies Evaluation Metrics (Transaction, Accounting, Reporting)
        // ==========================================================
        // Basic Properties
        [Required]
        [StringLength(FieldLengths.CurrencyCode)]
        public string CurrencyCode { get; set; } = string.Empty; // Transaction Currency Code

        // Transaction Currency Amounts (CUR)
        public decimal TaxBaseAmountCur { get; set; }
        public decimal TaxAmountCur { get; set; }

        // Accounting / Company Base Currency Amounts (MST)
        public decimal TaxBaseAmount { get; set; }
        public decimal TaxAmount { get; set; }

        // Secondary / Reporting Currency Amounts (REP)
        public decimal TaxBaseAmountRep { get; set; }
        public decimal TaxAmountRep { get; set; }

        // Quantity & Value Base Rates
        public decimal TaxBaseQty { get; set; }
        public decimal TaxValue { get; set; }

        // ==========================================================
        // Non-Deductible & Inventory Cost Loading Fields
        // ==========================================================
        // Basic Properties
        public decimal TaxInCostPrice { get; set; }
        public decimal TaxInCostPriceCur { get; set; }
        public decimal TaxInCostPriceMst { get; set; }
        public decimal TaxInCostPriceRep { get; set; }
        public decimal TaxInCostPriceRegulated { get; set; }

        // ==========================================================
        // Calculation Engines & Taxonomy Types
        // ==========================================================
        // Enum Properties
        public TaxAccountType TaxAccountType { get; set; }
        public TaxDirection TaxDirection { get; set; }
        public TaxOrigin TaxOrigin { get; set; }
        public TaxGroupSource Source { get; set; }
        public NoYes TaxAutoGenerated { get; set; }

        // ==========================================================
        // Exemptions, Deferred VAT & Cash Basis Frameworks
        // ==========================================================
        // Basic Properties
        [Required]
        [StringLength(FieldLengths.ExemptCode)]
        public string ExemptCode { get; set; } = string.Empty;

        public decimal VatExemptPct { get; set; }
        public DateTime RealizedDate { get; set; }

        // Enum Properties
        public NoYes ExemptTax { get; set; }
        public NoYes UnrealizedTax { get; set; }
        public NoYes UnrealizedTaxExt { get; set; }
        public NoYes PostponeVat { get; set; }

        // ==========================================================
        // Regional Regulatory Compliance & Regional Settings
        // ==========================================================
        // Basic Properties
        [Required]
        [StringLength(FieldLengths.PrintCode)]
        public string PrintCode { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.TaxJurisdictionCode)]
        public string TaxJurisdictionCode { get; set; } = string.Empty;

        [Required]
        [StringLength(FieldLengths.TaxPeriod)]
        public string TaxPeriod { get; set; } = string.Empty;

        public long TaxId { get; set; }
        public long PartyTaxId { get; set; }
        public long TaxBook { get; set; }
        public long TaxBookSection { get; set; }
        public int TaxRepCounter { get; set; }

        // Enum Properties
        public NoYes ReverseCharge_W { get; set; }
        public NoYes EuroTriangulation { get; set; }
        public NoYes EmptyTaxBaseForOutgoingTax_W { get; set; }
        public TaxObligationCompany TaxObligationCompany { get; set; }
        public TaxPrintDetail TaxPrintDetail { get; set; }

        // ==========================================================
        // Extensibility, System Audits & Discrepancy Indicators
        // ==========================================================
        // Basic Properties
        public long OrigTaxTransRecId { get; set; }
        public long TaxTransRefRecId { get; set; }
        public long ExchRateDiffOrigRecId { get; set; }
        public Guid IsvFeatureSetupGuid { get; set; }
        public int SysDataStateCode { get; set; }

        // Enum Properties
        public NoYes IsOverUnderpayment { get; set; }


        #region Navigation Properties Row

//         [ForeignKey(nameof(TaxCode))]
//         public virtual TaxTable? TaxCodeMaster { get; set; }

//         [ForeignKey(nameof(TaxGroup))]
//         public virtual TaxGroupHeading? AppliedTaxGroup { get; set; }

//         [ForeignKey(nameof(TaxItemGroup))]
//         public virtual TaxItemGroupHeading? AppliedTaxItemGroup { get; set; }

//         [ForeignKey(nameof(CurrencyCode))]
//         public virtual Currency? TransactionCurrency { get; set; }

//         [ForeignKey(nameof(SourceCurrencyCode))]
//         public virtual Currency? SourceCurrency { get; set; }

        #endregion
    }
}

